import {beginEdit,pendingReturn,finishReturn} from '../../shared/editable.mjs';
import {defaults,clean,cleanBlock,template} from './model.mjs?v=priority1';
import {workspace,downloadJSON,esc} from '../../shared/workspace.mjs?v=priority1';
const $=s=>document.querySelector(s);let state=defaults(),store;
function preview(){const solutions=$('#showSolutions').checked;$('#preview').innerHTML=`<h1>${esc(state.title)}</h1><p>${esc(state.subtitle)}</p><p class="sheet-meta">Nom: __________________________________ Data: ______________</p><p style="white-space:pre-wrap">${esc(state.instructions)}</p>`+state.blocks.map((b,i)=>`<section class="sheet-block"><h3>${i+1}. ${esc(b.title)}</h3><div>${esc(b.prompt)}</div>${b.image?`<img src="${b.image}" alt="${esc(b.title||'Esquema de l’activitat')}">`:''}${b.type==='question'?`<div class="answer-space" style="height:${b.space*85}px"></div>`:''}${b.solution?`<div class="sheet-solution" ${solutions?'':'hidden'}><b>Solució orientativa</b><br>${esc(b.solution)}</div>`:''}</section>`).join('')+(state.blocks.length?'':'<p class="no-print muted">Afegeix una activitat o envia un esquema des dels altres mòduls.</p>')}
function render(){for(const k of ['title','subtitle','instructions'])$('#'+k).value=state[k];$('#blockCount').textContent=`Blocs (${state.blocks.length}/30)`;$('#editors').innerHTML=state.blocks.map((b,i)=>`<div class="block-editor" data-id="${esc(b.id)}"><b>Bloc ${i+1} · ${b.type==='question'?'Activitat':b.type==='image'?'Imatge':'Text'}</b><label>Títol del bloc<input data-field="title" value="${esc(b.title)}" maxlength="160"></label><label>Enunciat / text<textarea data-field="prompt" maxlength="8000">${esc(b.prompt)}</textarea></label>${b.type!=='text'?`<label>Solució docent<textarea data-field="solution" maxlength="8000">${esc(b.solution)}</textarea></label>`:''}${b.type==='question'?`<label>Espai de resposta<select data-field="space">${['Sense espai','Curt','Mitjà','Llarg'].map((n,j)=>`<option value="${j}" ${b.space===j?'selected':''}>${n}</option>`).join('')}</select></label>`:''}<div class="actions">${b.source?'<button data-action="editSource">Edita al laboratori</button>':''}<button data-action="up" ${i===0?'disabled':''} aria-label="Puja el bloc ${i+1}">↑</button><button data-action="down" ${i===state.blocks.length-1?'disabled':''} aria-label="Baixa el bloc ${i+1}">↓</button><button data-action="copy">Duplica</button><button data-action="delete">Elimina</button></div></div>`).join('');preview()}
function persist(){try{const next=clean(state);state=next;store.save(state);$('#error').textContent=''}catch(e){$('#error').textContent=e.message}}
function add(blocks){try{const next=clean({...state,blocks:[...state.blocks,...blocks.map(b=>({...b,id:crypto.randomUUID()}))]});state=next;render();persist();return true}catch(e){$('#error').textContent=e.message;return false}}
function adapt(){const c=TechEduCurrent();$('#level').value=c.level;$('#showSolutions').checked=false;preview()}
store=workspace('worksheet',defaults,clean,s=>{state=s;render();adapt()});window.addEventListener('techedu-level',adapt);
for(const k of ['title','subtitle','instructions'])$('#'+k).oninput=e=>{state[k]=e.target.value;preview();persist()};
$('#editors').oninput=e=>{const field=e.target.dataset.field;if(!field)return;const b=state.blocks.find(b=>b.id===e.target.closest('[data-id]').dataset.id);b[field]=field==='space'?+e.target.value:e.target.value;preview();persist()};
$('#editors').onclick=e=>{const action=e.target.dataset.action;if(!action)return;const i=state.blocks.findIndex(b=>b.id===e.target.closest('[data-id]').dataset.id);if(action==='editSource'){try{if(store.save(state))beginEdit(state.blocks[i])}catch(err){$('#error').textContent=err.message}return}else if(action==='delete'){if(!confirm('Eliminar aquest bloc?'))return;state.blocks.splice(i,1)}else if(action==='copy'){add([state.blocks[i]]);return}else{const j=i+(action==='up'?-1:1);if(j<0||j>=state.blocks.length)return;[state.blocks[i],state.blocks[j]]=[state.blocks[j],state.blocks[i]]}render();persist()};
$('#addTemplate').onclick=()=>add([template($('#topic').value,$('#level').value)]);
$('#addQuestion').onclick=()=>add([cleanBlock({type:'question',title:'Nova activitat',prompt:'Escriu aquí l’enunciat.'})]);$('#addText').onclick=()=>add([cleanBlock({type:'text',title:'Orientacions',prompt:'Escriu aquí les instruccions.'})]);
$('#showSolutions').onchange=preview;
function print(teacher){const before=$('#showSolutions').checked;$('#showSolutions').checked=teacher;document.body.classList.toggle('print-teacher',teacher);preview();window.print();$('#showSolutions').checked=before;document.body.classList.remove('print-teacher');preview()}
$('#printStudent').onclick=()=>print(false);$('#printTeacher').onclick=()=>print(true);
$('#export').onclick=()=>downloadJSON({format:'techedu-worksheet',version:1,sheet:state},'techworksheet.json');
$('#new').onclick=()=>{if(!confirm('Començar una fitxa nova? Exporta abans l’actual si la vols conservar.'))return;state=defaults();render();persist()};
$('#import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>450000)throw Error('Fitxer massa gran.');const j=JSON.parse(await f.text());if(j.format!=='techedu-worksheet'||j.version!==1)throw Error('Format de fitxa no reconegut.');const next=clean(j.sheet);if(!confirm('Substituir la fitxa actual per la importada?'))return;state=next;render();persist()}catch(e){$('#error').textContent=e.message}finally{e.target.value=''}};
$('#imageInput').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>130000)throw Error('La imatge és massa gran. Utilitza un SVG o una imatge de menys de 130 kB.');if(!['image/png','image/jpeg','image/svg+xml'].includes(f.type))throw Error('Tria PNG, JPEG o SVG.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('No es pot llegir la imatge.'));r.readAsDataURL(f)});add([cleanBlock({type:'image',title:f.name.replace(/\.[^.]+$/,''),image:data})])}catch(e){$('#error').textContent=e.message}finally{e.target.value=''}};
try{const raw=sessionStorage.getItem('techedu.worksheet.transfer');if(raw){const t=JSON.parse(raw);if(t.owner===(TechEduProfiles.active()?.id||null)&&Array.isArray(t.blocks)){if(add(t.blocks))sessionStorage.removeItem('techedu.worksheet.transfer')}else $('#error').textContent='L’enviament pertany a un altre compte. Torna al compte d’origen per recuperar-lo.'}}catch(e){$('#error').textContent='No s’ha pogut incorporar l’activitat: '+e.message}

try{const t=pendingReturn();if(t){if(t.owner!==(TechEduProfiles.active()?.id||null))throw Error('El bloc retornat pertany a un altre compte.');const i=state.blocks.findIndex(b=>b.id===t.blockId);if(i<0||JSON.stringify(state.blocks[i])!==t.original)throw Error('El bloc original ha canviat. No s’ha substituït: conserva l’exportació del laboratori i revisa la fitxa.');if(confirm('Actualitzar el bloc amb les dades, l’enunciat i la solució del laboratori?')){const next=clean({...state,blocks:state.blocks.map((b,j)=>j===i?{...t.block,id:b.id}:b)});if(store.save(next)){state=next;render();finishReturn()}}else finishReturn()}}catch(e){$('#error').textContent=e.message}
