export const defaults=()=>({title:'Fitxa de Tecnologia',subtitle:'3r d’ESO',instructions:'Mostra el procediment i escriu les unitats de cada resultat.',blocks:[]});
export function cleanBlock(b){if(!b||typeof b!=='object'||!['question','text','image'].includes(b.type))throw Error('Tipus de bloc no reconegut.');const text=k=>typeof b[k]==='string'?b[k].slice(0,k==='title'?160:8000):'';const image=typeof b.image==='string'&&/^data:image\/(png|jpeg|svg\+xml);base64,[A-Za-z0-9+/=]+$/.test(b.image)&&b.image.length<=180000?b.image:'';if(b.type==='image'&&!image)throw Error('Imatge no vàlida o massa gran (màxim 180 kB en format de dades).');return {id:typeof b.id==='string'?b.id.slice(0,100):crypto.randomUUID(),type:b.type,title:text('title'),prompt:text('prompt'),solution:text('solution'),image,space:[0,1,2,3].includes(b.space)?b.space:1}}
export function clean(x){if(!x||typeof x!=='object'||!Array.isArray(x.blocks)||x.blocks.length>30)throw Error('La fitxa ha de contenir un màxim de 30 blocs.');const blocks=x.blocks.map(cleanBlock),ids=new Set();for(const b of blocks){if(ids.has(b.id))b.id=crypto.randomUUID();ids.add(b.id)}const s={...defaults(),...Object.fromEntries(['title','subtitle','instructions'].map(k=>[k,typeof x[k]==='string'?x[k].slice(0,k==='instructions'?4000:200):''])),blocks};if(JSON.stringify(s).length>390000)throw Error('La fitxa supera la mida disponible. Redueix les imatges.');return s}
export function template(topic,level){const guided=level==='guided',extension=level==='extension';const bank={
 electricity:{title:'Resistències en sèrie',prompt:'Una font ideal de 12 V alimenta R1 = 100 Ω i R2 = 200 Ω en sèrie, amb l’interruptor tancat. Calcula Req, I i la tensió a cada resistència.',guide:'1. Suma 100 + 200 per obtenir Req.\n2. Calcula I = 12 / Req.\n3. Calcula U1 = I × 100 i U2 = I × 200.\n4. Comprova que U1 + U2 = 12 V.',extra:'Connecta ara les mateixes resistències en paral·lel. Compara la intensitat i la potència total amb el cas anterior.',solution:'Sèrie: Req = 300 Ω; I = 0,04 A; U1 = 4 V; U2 = 8 V; P = 0,48 W.',advanced:'Paral·lel: Req = 66,667 Ω; I1 = 0,12 A; I2 = 0,06 A; I = 0,18 A; P = 2,16 W. La intensitat i la potència totals són 4,5 vegades més grans.'},
 lever:{title:'Una palanca en equilibri',prompt:'Una palanca de primer gènere suporta una resistència de 120 N a 0,25 m del fulcre. A l’altre costat apliquem una força perpendicular a 0,75 m. Quina força cal per equilibrar-la? Ignora el pes de la barra.',guide:'1. Identifica R = 120 N, bR = 0,25 m i bP = 0,75 m.\n2. Calcula el moment resistent: 120 × 0,25.\n3. Aplica P × 0,75 = R × 0,25.\n4. Divideix el moment resistent per 0,75.',extra:'Si només pots aplicar 30 N, a quina distància del fulcre has de fer la força? Justifica-ho amb els moments.',solution:'Moment resistent = 30 N·m. P = 30 / 0,75 = 40 N.',advanced:'Amb P = 30 N, bP = 30 / 30 = 1 m.'},
 logic:{title:'Control d’un ventilador',prompt:'Un ventilador s’activa si hi ha temperatura alta (T) i la finestra és tancada (F). Escriu la funció i la taula de veritat.',guide:'1. Escriu les quatre combinacions TF: 00, 01, 10, 11.\n2. Només activa la sortida quan totes dues condicions valen 1.\n3. Escriu la funció amb AND (·).',extra:'Afegeix un comandament manual M que activa el ventilador independentment de T i F. Escriu la funció i explica què passa quan M = 1.',solution:'S = T · F. Per TF = 00, 01, 10, 11, la sortida és 0, 0, 0, 1.',advanced:'S = (T · F) + M. Amb M = 1, S = 1 per a qualsevol T i F.'},
 materials:{title:'Tria un material per a un cable',prompt:'Tria entre coure, PVC i vidre per al conductor i per a la coberta flexible d’un cable elèctric. Justifica cada elecció amb una propietat.',guide:'1. El conductor ha de deixar passar el corrent: quin material és conductor?\n2. La coberta ha d’aïllar i doblegar-se: quin material compleix les dues condicions?\n3. Explica per què descartes el vidre.',extra:'Explica per què la conductivitat elèctrica no basta per triar la coberta: afegeix dos criteris mecànics o de fabricació.',solution:'Conductor: coure, bon conductor elèctric i dúctil. Coberta: PVC, aïllant elèctric i flexible segons la formulació. El vidre és aïllant però fràgil i poc adequat per a un cable flexible.',advanced:'Cal considerar flexibilitat, resistència a l’abrasió, durabilitat i facilitat d’extrusió. S’accepten altres criteris justificats.'}
 };const a=bank[topic];if(!a)throw Error('Plantilla desconeguda.');return cleanBlock({type:'question',title:a.title,prompt:a.prompt+(guided?'\n\n'+a.guide:'')+(extension?'\n\nAmpliació: '+a.extra:''),solution:a.solution+(extension?'\n'+a.advanced:''),space:guided?2:1})}
