const assert=require('node:assert/strict'),fs=require('node:fs');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),BASE=process.env.BASE_URL||'http://localhost:8767';
(async()=>{const b=await chromium.launch({args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1600,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto(BASE+'/modules/drawings/');await p.locator('.nav-item').filter({hasText:'Cordes i elevació'}).click();await p.locator('.example-card').filter({hasText:'Politja amb càrrega connectada'}).click();
const field=k=>p.locator('[data-property="'+k+'"]');const read=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('techdrawings.v1')));const ropePath=()=>p.locator('#scene .object').first().locator('path').getAttribute('d');const initial=await ropePath();await p.locator('#scene .object').last().locator('rect').click();await field('x').fill('550');await field('x').press('Tab');assert.notEqual(await ropePath(),initial);const moved=await ropePath();await p.reload();assert.equal(await ropePath(),moved);
// A selection-only click must not detach the rope.
const rope=await read();const ropeId=rope.objects.find(o=>o.kind==='rope').id;await p.locator('#scene [data-id="'+ropeId+'"] path').click();assert.ok((await read()).objects.find(o=>o.kind==='rope').endConnection);await p.locator('[data-connection="end"]').selectOption('');assert.equal(await ropePath(),moved);assert.equal((await read()).objects.find(o=>o.kind==='rope').endConnection,undefined);await p.locator('#undoBtn').click();assert.ok((await read()).objects.find(o=>o.kind==='rope').endConnection);
await p.locator('#scene .object').last().locator('rect').click();await p.locator('#deleteObj').click();assert.equal(await ropePath(),moved);await p.locator('#undoBtn').click();assert.equal(await ropePath(),moved);
// Configurable pulley changes connected rope geometry.
const data=await read(),pulleyId=data.objects.find(o=>o.kind==='fixedpulley').id;await p.locator('#scene [data-id="'+pulleyId+'"] text').first().click();await field('ropeLengthA').fill('250');await field('ropeLengthA').press('Tab');await field('ropeAngleA').fill('45');await field('ropeAngleA').press('Tab');assert.notEqual(await ropePath(),moved);
await p.locator('.nav-item').filter({hasText:'Cordes i elevació'}).click();await p.locator('.piece-card').filter({hasText:'De 2 a 8 politges'}).click();await field('pairs').selectOption('4');const selected=(await read()).objects.find(o=>o.kind==='tackle');assert.equal(await p.locator('#scene [data-id="'+selected.id+'"] circle').count(),17);await field('blockGap').fill('240');await field('blockGap').press('Tab');
// Connect using two visible ports, then export/import with remapped IDs.
await p.locator('[data-tool="connect"]').click();await p.locator('[data-target="'+pulleyId+'"][data-port="b"]').click();await p.locator('[data-target="'+selected.id+'"][data-port="effort"]').click();assert.equal((await read()).objects.filter(o=>o.kind==='rope').length,2);assert.ok((await read()).objects.filter(o=>o.kind==='rope').at(-1).endConnection);
await p.locator('#exportBtn').click();const download=p.waitForEvent('download');await p.locator('[data-export="json"]').click();const d=await download,file=await d.path();const saved=JSON.parse(fs.readFileSync(file,'utf8'));await p.locator('#importInput').setInputFiles(file);const restored=await read();assert.equal(restored.objects.length,saved.objects.length);assert.notEqual(restored.objects[0].id,saved.objects[0].id);for(const r of restored.objects.filter(o=>o.kind==='rope'))for(const side of ['start','end'])if(r[side+'Connection'])assert.ok(restored.objects.some(o=>o.id===r[side+'Connection'].objectId));
await p.locator('.nav-item').filter({hasText:'Màquines simples'}).click();await p.locator('.piece-card').filter({hasText:'Barra amb fulcre'}).click();await field('showLoad').check();const lever=(await read()).objects.find(o=>o.kind==='lever');assert.equal(await p.locator('#scene [data-id="'+lever.id+'"] rect').count(),1);await field('showLoad').uncheck();assert.equal(await p.locator('#scene [data-id="'+lever.id+'"] rect').count(),0);
await p.locator('.nav-item').filter({hasText:'Cordes i elevació'}).click();await p.locator('.example-card').filter({hasText:'Polispast de quatre'}).click();await p.screenshot({path:'/tmp/techedu-rigging-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await p.locator('.suite-nav a[aria-current]').textContent(),'Tecnofigures');await p.screenshot({path:'/tmp/techedu-rigging-mobile.png',fullPage:true});assert.deepEqual(errors,[]);await b.close();console.log('Rigging controls, connections, target moves/deletion, undo, pulley angles, tackles, JSON remapping, lever load and mobile UI OK');})().catch(e=>{console.error(e);process.exit(1)});
