const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const BASE=process.env.BASE_URL||'http://localhost:8766';
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const context=await browser.newContext(),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const set=async(id,value)=>page.locator('#'+id).evaluate((el,value)=>{el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));},String(value));
 await page.goto(BASE+'/profiles/');await page.locator('#newName').fill('Prova senyals A');await page.locator('#addForm button').click();
 await page.locator('[data-domain="communications"]').selectOption('guided');
 await page.locator('[data-test="communications"]').click();assert.equal(await page.locator('.test-question').count(),6);
 await page.locator('#newName').fill('Prova senyals B');await page.locator('#addForm button').click();await page.locator('[data-domain="communications"]').selectOption('extension');
 await page.locator('#profileList button').first().click();
 await page.goto(BASE+'/modules/communications/');
 assert.equal(await page.locator('#reveal').isChecked(),false);assert.equal(await page.locator('#showSteps').isChecked(),true);
 await page.locator('#loadChallenge').click();await page.locator('#bitPrediction').selectOption('zero');await page.locator('#checkPrediction').click();assert.match(await page.locator('#predictionFeedback').textContent(),/Correcte/);
 await page.locator('#pinBaseline').click();await set('gain',.3);await page.locator('#reveal').check();assert.match(await page.locator('#metrics').textContent(),/4\/8/);assert.match(await page.locator('#comparisonResult').textContent(),/Prova A: 0\/8.*Prova B: 4\/8/);
 await set('threshold',.15);assert.match(await page.locator('#metrics').textContent(),/0\/8/);
 await page.locator('#workConclusion').fill('0,30 V supera 0,15 V: es recuperen els bits 1.');
 await page.locator('#workFinish').click();await page.reload();assert.equal(await page.locator('#gain').inputValue(),'0.3');assert.equal(await page.locator('#threshold').inputValue(),'0.15');assert.match(await page.locator('#comparisonResult').textContent(),/Prova A: 0\/8/);assert.match(await page.locator('#workConclusion').inputValue(),/recuperen/);
 const selector=page.locator('.techedu-profile-bar select'),ids=await selector.locator('option').evaluateAll(es=>es.map(e=>e.value));
 await page.locator('.account-menu').evaluate(el=>el.open=true);await selector.selectOption(ids[2]);assert.equal(await page.locator('#workConclusion').inputValue(),'');assert.equal(await page.locator('#gain').inputValue(),'1');assert.match(await page.locator('#comparisonSummary').textContent(),/Encara/);
 await page.locator('#loadChallenge').click();assert.equal(await page.locator('#noise').inputValue(),'0.25');await page.locator('.controls details summary').click();await page.locator('#newNoise').click();assert.equal(await page.locator('#seed').inputValue(),'43');
 await page.locator('.account-menu').evaluate(el=>el.open=true);await selector.selectOption(ids[1]);assert.equal(await page.locator('#threshold').inputValue(),'0.15');assert.match(await page.locator('#workConclusion').inputValue(),/recuperen/);
 await page.locator('#reveal').uncheck();assert.equal(await page.locator('#results').isVisible(),false);assert.match(await page.locator('#comparisonResult').textContent(),/Mostra les mesures/);
 await page.locator('#bits').fill('invalid');assert.equal(await page.locator('#inputError').isVisible(),true);assert.equal(await page.locator('#wave').isVisible(),false);await page.locator('#bits').fill('10110010');
 await page.locator('[data-preset="analog"]').click();assert.equal(await page.locator('#analogControls').isVisible(),true);assert.equal(await page.locator('#receiverControls').isVisible(),false);await page.locator('#reveal').check();assert.equal(await page.locator('#bitResults').isVisible(),false);assert.match(await page.locator('#metrics').textContent(),/RMS/);
 await page.locator('.work-session summary').click();await page.locator('#workHistory button').first().click();assert.equal(await page.locator('#mode').inputValue(),'digital');assert.equal(await page.locator('#threshold').inputValue(),'0.15');
 await page.screenshot({path:process.env.SCREENSHOT||'/tmp/techedu-signals-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await page.screenshot({path:'/tmp/techedu-signals-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log('CommunicationsLab: thresholds, comparisons, hidden results, profiles, reload, evidence, modes and mobile layout OK');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
