const assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const BASE=process.env.BASE_URL||'http://localhost:8767';
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(BASE+'/');assert.equal(await page.locator('#modules a[href*="profiles"]').count(),0);assert.equal(await page.locator('.suite-header').count(),1);assert.match(await page.locator('#modules').textContent(),/Tecnofigures/);
 // Old profile migrates without changing supports or losing existing notebook.
 await page.evaluate(()=>localStorage.setItem('techedu.profiles.v1',JSON.stringify({version:1,metaRevision:0,activeId:'old',profiles:[{id:'old',name:'ESO A',level:'extension',domains:{},supports:{stepByStep:true},attempts:[],work:{materials:{revision:1,draft:{fields:{workConclusion:'Anterior'}}}}}]})));
 await page.goto(BASE+'/profiles/');await page.waitForURL('**/account/');assert.equal(await page.locator('#course').inputValue(),'eso');assert.equal(await page.locator('#generalLevel').inputValue(),'extension');assert.ok(await page.locator('#stepByStep').isChecked());
 await page.locator('#newName').fill('Batx B');await page.locator('#addForm button').click();await page.locator('#course').selectOption('batx');await page.locator('#generalLevel').selectOption('extension');const ids=await page.locator('#profileList button').evaluateAll(es=>es.map(e=>e.dataset.id));
 const choose=async id=>{await page.locator('.account-menu').evaluate(el=>el.open=true);await page.getByLabel('Compte actiu',{exact:true}).selectOption(id)};
 await page.goto(BASE+'/modules/communications/errors.html');await page.locator('#loadChallenge').click();assert.equal(await page.locator('#method').inputValue(),'checksum');assert.match(await page.locator('#activityTitle').textContent(),/comprovació correcta/);await choose(ids[0]);await page.locator('#loadChallenge').click();assert.equal(await page.locator('#method').inputValue(),'parity');assert.match(await page.locator('#activityTitle').textContent(),/límit de la paritat/);assert.match(await page.locator('.learning-route').textContent(),/3r D’ESO/);
 await page.goto(BASE+'/modules/communications/digitization.html');await page.locator('#loadChallenge').click();assert.equal(await page.locator('#frequency').inputValue(),'3');await choose(ids[1]);await page.locator('#loadChallenge').click();assert.equal(await page.locator('#frequency').inputValue(),'7');
 await page.goto(BASE+'/modules/logic/');assert.ok(await page.locator('[data-course-extra]').first().getAttribute('open')!==null);await choose(ids[0]);assert.equal(await page.locator('[data-course-extra]').first().getAttribute('open'),null);await page.locator('#loadLevel').click();assert.equal(await page.locator('#expr1').inputValue(),'A & B & !C');
 await page.goto(BASE+'/modules/drawings/');await page.locator('.piece-card').first().click();await page.locator('#docTitle').fill('Esquema ESO');await page.locator('#docTitle').press('Tab');await choose(ids[1]);assert.equal(await page.locator('#objectCount').textContent(),'0 elements');await page.locator('.piece-card').first().click();await page.locator('#docTitle').fill('Esquema Batx');await page.locator('#docTitle').press('Tab');await choose(ids[0]);assert.equal(await page.locator('#docTitle').inputValue(),'Esquema ESO');await page.reload();assert.equal(await page.locator('#docTitle').inputValue(),'Esquema ESO');
 await page.goto(BASE+'/account/');const download=page.waitForEvent('download');await page.locator('#exportData').click();const d=await download;const data=JSON.parse(require('node:fs').readFileSync(await d.path(),'utf8'));assert.equal(data.profiles[0].work.drawings.draft.extra.document.title,'Esquema ESO');assert.equal(data.profiles[1].course,'batx');assert.equal(data.profiles[0].work.materials.draft.fields.workConclusion,'Anterior');
 const pages=['/','/account/','/modules/drawings/','/modules/mechanisms/','/modules/materials/','/modules/problems/','/modules/logic/','/modules/communications/','/modules/communications/encoding.html','/modules/communications/digitization.html','/modules/communications/errors.html','/modules/communications/packets.html'];
 await page.setViewportSize({width:390,height:844});for(const path of pages){await page.goto(BASE+path);assert.equal(await page.locator('.suite-header').count(),1,path);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),path+' overflows');}
 await page.goto(BASE+'/');await page.screenshot({path:'/tmp/techedu-account-home-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.goto(BASE+'/modules/drawings/');await page.screenshot({path:'/tmp/techedu-tecnofigures.png',fullPage:true});await page.goto(BASE+'/account/');await page.screenshot({path:'/tmp/techedu-account.png',fullPage:true});assert.deepEqual(errors,[]);await browser.close();console.log('Account migration, course/support independence, differentiated tasks, drawing isolation, export and responsive suite OK');
})().catch(e=>{console.error(e);process.exit(1)});
