import {defaults,clean,solve,schematic,fmt} from './model.mjs';
import {workspace,downloadJSON,sendToWorksheet} from '../../shared/workspace.mjs?v=priority1';
import {installReturn} from '../../shared/editable.mjs';
const $=s=>document.querySelector(s);let state=defaults(),store;
function render(){for(const k of ['kind','length','position','load','height','deformation'])$('#'+k).value=state[k];$('#showValues').checked=state.showValues;$('#heightLabel').hidden=state.kind!=='truss';$('#deformationLabel').hidden=state.kind!=='beam';$('#diagram').innerHTML=schematic(state);const r=solve(state);$('#interpretation').textContent=state.kind==='beam'?'La biga treballa a flexió i tallant. Amb càrrega cap avall: fibres superiors comprimides i inferiors traccionades; sense esforç axial resultant.':'Amb càrrega al nus superior: diagonals comprimides i tirant inferior traccionat. Amb càrrega nul·la, tots els esforços són nuls.';$('#equilibrium').textContent=state.showValues?`RA + RB = ${fmt(r.RA+r.RB)} N = P. RB·L = P·a = ${fmt(r.P*r.a)} N·m.`:'Escales dels diagrames normalitzades per veure’n la forma. Activa els valors per comparar magnituds.';guide()}
function guide(){const level=TechEduCurrent().level;$('#guide').textContent=level==='guided'?'1. Situa a/L = 0,5. Les reaccions seran iguals? 2. Mostra els valors. 3. Canvia només a/L a 0,25. Quin recolzament suporta més càrrega? Anota RA i RB abans i després.':level==='extension'?'Deduïx RA i RB prenent moments. A l’encavallada, mantén L i P i redueix h a la meitat: com varia l’esforç del tirant? Justifica-ho amb l’equilibri d’un nus.':state.kind==='beam'?'Compara a/L = 0,5 i 0,25 mantenint L i P. Explica el canvi de les reaccions i del moment màxim; després comprova què passa en duplicar P.':'Compara a/L = 0,5 i 0,25 mantenint L, h i P. Explica el canvi de les reaccions i dels esforços de les barres.'}
store=workspace('structures',defaults,clean,s=>{state=s;render()});window.addEventListener('techedu-level',guide);
for(const k of ['kind','length','position','load','height','deformation','showValues'])$('#'+k).onchange=e=>{try{state=clean({...state,[k]:k==='kind'?e.target.value:k==='showValues'?e.target.checked:Number(e.target.value)});render();store.save(state);$('#error').textContent=''}catch(err){$('#error').textContent=err.message;render()}};

$('#reset').onclick=()=>{if(confirm('Reiniciar el model i les respostes d’aquest experiment?')){state=defaults();render();store.save(state)}};
$('#export').onclick=()=>downloadJSON({format:'techedu-structure',version:1,state},'structurelab.json');
$('#import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>50000)throw Error('Fitxer massa gran.');const j=JSON.parse(await f.text());if(j.format!=='techedu-structure'||j.version!==1)throw Error('Format no reconegut.');const s=clean(j.state);if(confirm('Substituir l’experiment actual?')){state=s;render();store.save(state)}}catch(err){$('#error').textContent=err.message}finally{e.target.value=''}};
function block(){const r=solve(state);return {type:'question',title:state.kind==='beam'?'Biga recolzada':'Encavallada triangular',prompt:`L = ${fmt(state.length)} m; P = ${fmt(state.load)} N; a = ${fmt(r.a)} m; h = ${fmt(state.height)} m. Prediu quin suport rep més càrrega. Calcula les reaccions i explica els esforços.`,solution:`RA = ${fmt(r.RA)} N; RB = ${fmt(r.RB)} N. `+(state.kind==='beam'?`M màxim = ${fmt(r.maxMoment)} N·m.`:r.members.map(m=>`${m.name}: ${fmt(m.force)} N (positiu: tracció)`).join('; ')),image:'data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(schematic({...state,showValues:false})))),space:2,source:{module:'structures',version:1,state}}}
$('#worksheet').onclick=()=>{try{sendToWorksheet([block()])}catch(e){$('#error').textContent=e.message}};installReturn('structures',block);
