export const defaults=()=>({kind:'beam',length:4,position:.5,load:1000,height:2,showValues:false,deformation:35,prediction:'',conclusion:''});
export function clean(x){if(!x||typeof x!=='object')throw Error('Model no vàlid.');const s={...defaults(),...x};if(!['beam','truss'].includes(s.kind))throw Error('Tipus desconegut.');for(const [k,min,max] of [['length',1,12],['position',.1,.9],['load',0,10000],['height',.5,6],['deformation',0,80]])if(typeof s[k]!=='number'||!Number.isFinite(s[k])||s[k]<min||s[k]>max)throw Error('Valor fora de rang: '+k);return {kind:s.kind,length:s.length,position:s.position,load:s.load,height:s.height,deformation:s.deformation,showValues:!!s.showValues,prediction:String(s.prediction||'').slice(0,4000),conclusion:String(s.conclusion||'').slice(0,4000)}}
export function solve(input){const s=clean(input),L=s.length,a=L*s.position,P=s.load,b=L-a,RA=P*b/L,RB=P*a/L;return {L,a,P,RA,RB,maxMoment:P*a*b/L,shearLeft:RA,shearRight:-RB,moment:x=>RA*x-P*Math.max(0,x-a),members:[{name:'AC',force:-RA*Math.hypot(a,s.height)/s.height},{name:'BC',force:-RB*Math.hypot(b,s.height)/s.height},{name:'AB',force:RA*a/s.height}]}}
export const fmt=n=>Number(n.toFixed(2)).toLocaleString('ca');
export function schematic(input){const s=clean(input),r=solve(s),left=90,right=710,X=left+620*s.position,Y=210,H=Math.min(160,620*s.height/s.length),top=Y-H,c='#264a58';
const text=(x,y,t)=>`<text x="${x}" y="${y}" text-anchor="middle" font-family="sans-serif" font-size="16" fill="${c}">${t}</text>`;
const line=(x,y,x2,y2,color=c,width=4)=>`<line x1="${x}" y1="${y}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="${width}"/>`;
const arrow=(x,y,end,color)=>line(x,y,x,end,color,3)+`<path d="M${x-6} ${end+(end>y?-10:10)} L${x} ${end} L${x+6} ${end+(end>y?-10:10)}" fill="none" stroke="${color}" stroke-width="3"/>`;
let g=`<path d="M90 212 l-18 25 h36 Z M710 212 l-18 25 h36 Z" fill="white" stroke="${c}" stroke-width="2"/><circle cx="701" cy="243" r="5" fill="none" stroke="${c}"/><circle cx="719" cy="243" r="5" fill="none" stroke="${c}"/>`+text(left,270,'A · articulació')+text(right,270,'B · corró')+arrow(left,310,250,'#315e53')+arrow(right,310,250,'#315e53')+text(left,335,s.showValues?`RA = ${fmt(r.RA)} N`:'Reacció A')+text(right,335,s.showValues?`RB = ${fmt(r.RB)} N`:'Reacció B');
if(s.kind==='beam'){
g+=line(left,Y,right,Y)+arrow(X,115,200,'#b64e22')+text(X,95,`P = ${fmt(s.load)} N`)+text(400,35,`Biga · L = ${fmt(s.length)} m · a = ${fmt(r.a)} m`);
if(s.deformation&&s.load)g+=`<path d="M90 210 Q${X} ${210+s.deformation*2} 710 210" fill="none" stroke="#9a642f" stroke-width="3" stroke-dasharray="7 5"/>`;
g+=text(400,375,'Traç discontinu: deformació il·lustrativa, no calculada');
const vscale=s.load?55/s.load:0,mscale=r.maxMoment?60/r.maxMoment:0;
g+=line(left,455,right,455,'#9ba8ac',1)+`<path d="M90 455 V${455-r.RA*vscale} H${X} V${455+r.RB*vscale} H710 V455" fill="none" stroke="#176773" stroke-width="3"/>`+text(400,420,'Tallant V · positiu sobre l’eix')+text(210,535,s.showValues?`V esquerra = ${fmt(r.RA)} N`:'V esquerra ≥ 0')+text(590,535,s.showValues?`V dreta = ${fmt(-r.RB)} N`:'V dreta ≤ 0');
g+=line(left,650,right,650,'#9ba8ac',1)+`<path d="M90 650 L${X} ${650-r.maxMoment*mscale} L710 650" fill="none" stroke="#b64e22" stroke-width="3"/>`+text(400,570,'Moment flector M · positiu: flexió còncava cap amunt')+text(400,685,s.showValues?`M màxim = ${fmt(r.maxMoment)} N·m`:'M nul als recolzaments; màxim sota la càrrega');
}else{
const coords=[[left,Y,X,top],[right,Y,X,top],[left,Y,right,Y]];r.members.forEach((m,i)=>{const [x,y,x2,y2]=coords[i],color=m.force<0?'#b64e22':m.force>0?'#176773':'#68777b';g+=line(x,y,x2,y2,color,7)+text((x+x2)/2,(y+y2)/2+(i===2?-12:-15),m.name+' · '+(m.force<0?'compressió':m.force>0?'tracció':'nul')+(s.showValues?' '+fmt(Math.abs(m.force))+' N':''))});g+=arrow(X,top-55,top-8,'#b64e22')+text(X,top-65,`C · P = ${fmt(s.load)} N`)+text(400,375,`L = ${fmt(s.length)} m · h = ${fmt(s.height)} m · a = ${fmt(r.a)} m`)+text(400,415,'Barres articulades · esquema no a escala · sense deformació calculada.');
}
return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 ${s.kind==='truss'?-100:0} 800 ${s.kind==='beam'?720:560}" role="img" aria-label="${s.kind==='beam'?'Biga, reaccions i diagrames de tallant i moment':'Encavallada triangular: tracció i compressió'}"><rect x="0" y="-100" width="800" height="900" fill="white"/>${g}</svg>`}
