const $=s=>document.querySelector(s),rnd=(a,b)=>Math.round((a+Math.random()*(b-a))*10)/10,ri=(a,b)=>Math.floor(a+Math.random()*(b-a+1));
function problem(type,d){if(type==='mixed')type=['lever','gears','ohm','energy','multigear'][ri(0,4)];if(type==='multigear'){const z1=ri(10,30),z2=ri(30,70),z3=ri(12,35),z4=ri(35,80),n1=ri(8,28)*50,n2=n1*z1/z2,n4=Math.round(n2*z3/z4);return {title:'Tren compost d’engranatges',q:`Un motor gira a <b>${n1} rpm</b>. L’engranatge 1 (${z1} dents) mou el 2 (${z2}); al mateix eix del 2 hi ha el 3 (${z3}), que mou el 4 (${z4}). Calcula la velocitat final i determina si el sistema redueix o multiplica la velocitat.`,guide:['Calcula primer n₂ amb n₁·z₁=n₂·z₂.','Recorda que els engranatges 2 i 3 comparteixen eix: n₂=n₃.','Aplica la relació de transmissió entre 3 i 4.','Compara n₄ amb n₁.'],s:`n₂=${Math.round(n2)} rpm; n₃=n₂; n₄=(n₃·${z3})/${z4}=<b>${n4} rpm</b>. És un sistema ${n4<n1?'reductor':'multiplicador'}.`};}if(type==='lever'){
  const genre=ri(1,3), P=ri(8,40)*10;
  // Lengths in tenths of a metre guarantee the correct physical order.
  const bp10=genre===2?ri(8,20):genre===3?ri(3,9):ri(5,18);
  const br10=genre===2?ri(2,bp10-2):genre===3?ri(bp10+2,20):ri(5,18);
  const model=LeverModel.create(genre,P,bp10/10,br10/10);
  const {num,svg}=LeverModel;
  return {guide:['Localitza al dibuix el fulcre, P i R. Comprova que el punt central correspon al gènere indicat.','Mesura els dos braços des del fulcre, no des de l’extrem de la barra.','Escriu la condició d’equilibri P·bₚ = R·bᵣ i aïlla R.'],title:`Palanca de ${genre}r gènere`,diagram:svg(model),q:`La potència és de <b>${P} N</b> i actua a <b>${num(model.bp)} m</b> del fulcre. La resistència és a <b>${num(model.br)} m</b>. Calcula R per mantenir l’equilibri. Indica quin element queda entre els altres dos.`,s:`P·bₚ = R·bᵣ → R = (${P}·${num(model.bp)})/${num(model.br)} = <b>${num(model.resistance)} N</b>.`};
}if(type==='gears'){const z1=ri(10,40),z2=ri(20,80),n1=ri(5,30)*50,n2=Math.round(n1*z1/z2);return {guide:['Identifica roda motriu i conduïda.','Relaciona velocitat i nombre de dents.','Comprova si la roda més gran ha de girar més ràpid o més lent.'],title:'Transmissió per engranatges',q:`Una roda motriu de <b>${z1} dents</b> gira a <b>${n1} rpm</b> i engrana amb una roda de <b>${z2} dents</b>. Calcula la velocitat de la roda conduïda i indica el sentit de gir.`,s:`n₁·z₁=n₂·z₂ → n₂=(${n1}·${z1})/${z2}=<b>${n2} rpm</b>. Dues rodes en contacte giren en sentits contraris.`};}if(type==='ohm'){const R=ri(2,20)*5,I=rnd(.2,3),V=Math.round(R*I*10)/10;return {guide:['Escriu la llei d’Ohm.','Identifica quina magnitud és la incògnita.','Comprova les unitats abans de calcular.'],title:"Llei d'Ohm",q:`Per una resistència de <b>${R} Ω</b> circula un corrent de <b>${I} A</b>. Calcula la tensió aplicada.`,s:`V=R·I=${R}·${I}=<b>${V} V</b>.`};}const Ein=ri(2,20)*100,Eout=Math.round(Ein*rnd(.55,.92)),eta=Math.round(Eout/Ein*1000)/10;return {guide:['Diferencia energia d’entrada, útil i dissipada.','Calcula primer el quocient Eútil/Eentrada.','Expressa el rendiment en percentatge.'],title:'Rendiment energètic',q:`Una màquina rep <b>${Ein} J</b> i transforma <b>${Eout} J</b> en energia útil. Calcula el rendiment i l'energia dissipada.`,s:`η=Eútil/Eentrada·100=<b>${eta}%</b>. Edissipada=${Ein}-${Eout}=<b>${Ein-Eout} J</b>.`};}
function render(){const n=Math.min(30,Math.max(1,+$('#count').value||1)),show=$('#solutions').checked;$('#output').innerHTML=Array.from({length:n},(_,i)=>{const p=problem($('#topic').value,+$('#difficulty').value);const guide=$('#guided').checked&&p.guide?`<div class="solution"><b>Guia de raonament</b><ol>${p.guide.map(x=>`<li>${x}</li>`).join('')}</ol></div>`:'';return `<article><small>VARIANT ${i+1}</small><h2>${p.title}</h2><p>${p.q}</p>${p.diagram||''}${guide}${show?`<div class="solution"><b>Resolució</b><p>${p.s}</p></div>`:''}</article>`}).join('')}$('#generate').onclick=render;$('#solutions').onchange=render;$('#guided').onchange=render;render();