import {clean as cleanCircuit} from '../modules/circuits/model.mjs';
import {clean as cleanStructure} from '../modules/structures/model.mjs';
const KEY='techedu.worksheet.edit';
export function cleanSource(source){if(!source)return null;if(source.version!==1||!['drawings','circuits','structures'].includes(source.module))throw Error('Origen editable desconegut.');if(JSON.stringify(source).length>180000)throw Error('Origen editable massa gran.');const s=source.state;let state;if(source.module==='circuits'){if(!s||!['series','parallel','mixed'].includes(s.topology)||!Number.isFinite(s.voltage)||s.voltage<0||s.voltage>48||!Array.isArray(s.resistors)||s.resistors.length<2||s.resistors.length>4||s.resistors.some(r=>!Number.isFinite(r)||r<1||r>100000)||(s.topology==='mixed'&&s.resistors.length!==3))throw Error('Circuit editable no vàlid.');state=cleanCircuit(s);}else if(source.module==='structures')state=cleanStructure(s);else{if(!s||typeof s.title!=='string'||!Array.isArray(s.objects)||s.objects.length>500||!s.objects.every(o=>o&&typeof o.id==='string'&&typeof o.kind==='string'&&Number.isFinite(o.x)&&Number.isFinite(o.y)))throw Error('Dibuix editable no vàlid.');state=JSON.parse(JSON.stringify(s));}return {module:source.module,version:1,state}}
export function editContext(module){if(new URLSearchParams(location.search).get('edit')!=='worksheet')return null;const c=JSON.parse(sessionStorage.getItem(KEY)||'null');if(!c||c.owner!==(TechEduProfiles.active()?.id||null)||c.module!==module)throw Error('L’edició no correspon al compte actiu. Torna a la fitxa.');return c}
export function saveEdit(module,state){const c=editContext(module);if(!c)return false;c.source=cleanSource({module,version:1,state});sessionStorage.setItem(KEY,JSON.stringify(c));return true}
export function beginEdit(block){const source=cleanSource(block.source);if(!source)return;sessionStorage.setItem(KEY,JSON.stringify({owner:TechEduProfiles.active()?.id||null,module:source.module,source,blockId:block.id,original:JSON.stringify(block)}));location.href=new URL('../'+source.module+'/?edit=worksheet',location.href).href}
export function installReturn(module,makeBlock){if(new URLSearchParams(location.search).get('edit')!=='worksheet')return;const bar=document.createElement('section');bar.className='suite-edit-banner no-print';bar.innerHTML='<strong>Edició d’una còpia de la fitxa. El projecte del laboratori es conserva.</strong><button data-return>Actualitza el bloc i torna</button><button data-cancel>Torna sense aplicar</button><p role="status"></p>';document.querySelector('header').after(bar);document.querySelectorAll('#worksheet,[data-export=worksheet]').forEach(e=>e.hidden=true);document.querySelector('a[href="#learningJourney"]')?.closest('p')?.setAttribute('hidden','');window.TechEduBeforeAccountChange=()=>{bar.querySelector('p').textContent='Torna a la fitxa o aplica el bloc abans de canviar de compte o nivell.';return false};bar.querySelector('[data-cancel]').onclick=()=>{sessionStorage.removeItem(KEY);location.href=new URL('../worksheet/',location.href).href};bar.querySelector('[data-return]').onclick=()=>{try{const c=editContext(module),block=makeBlock();sessionStorage.setItem('techedu.worksheet.return',JSON.stringify({...c,block}));location.href=new URL('../worksheet/',location.href).href}catch(e){bar.querySelector('p').textContent=e.message}};window.addEventListener('techedu-level',()=>{try{editContext(module)}catch(e){bar.querySelector('[data-return]').disabled=true;bar.querySelector('p').textContent=e.message}})}
export function pendingReturn(){const raw=sessionStorage.getItem('techedu.worksheet.return');return raw?JSON.parse(raw):null}
export function finishReturn(){sessionStorage.removeItem('techedu.worksheet.return');sessionStorage.removeItem(KEY)}
