(function(){
 const path=location.pathname;const kind=path.includes('/communications/')?(path.endsWith('encoding.html')?'encoding':path.endsWith('digitization.html')?'digitization':path.endsWith('errors.html')?'errors':path.endsWith('packets.html')?'packets':'signals'):path.split('/modules/')[1]?.split('/')[0];
 const content={
 drawings:['Explica una situació amb un esquema','Representa forces, esforços, estructures o una màquina simple. Cada fletxa i cada etiqueta han d’ajudar a entendre el dibuix.','Tria Esforços → Flexió d’una biga. Identifica els dos suports i la càrrega. Mou la fletxa i explica on actua; el dibuix no calcula la deformació.','Un esquema amb títol, elements etiquetats i una frase que expliqui l’esforç.','Força|Empenta o estirada, representada amb una fletxa.;Fulcre|Punt de suport d’una palanca.;Esforç|Manera com treballa una peça: tracció, compressió, flexió, torsió o cisallament.'],
 mechanisms:['Relaciona dents, gir i velocitat','Compara dues rodes dentades abans d’encadenar transmissions. Una rpm és una volta per minut.','Prem Demo. Localitza la motriu. Si la conduïda té el doble de dents, prediu si girarà més de pressa o més a poc a poc; simula i comprova les rpm.','Nombre de dents de cada roda, rpm d’entrada i sortida i sentit de gir.','Motriu|Roda que rep el moviment del motor.;Conduïda|Roda que rep el moviment de la motriu.;Relació|n₂ = n₁ × z₁ / z₂ en dues rodes dentades.'],
 problems:['Resol i comprova amb unitats','Practica palanques, engranatges, electricitat i energia. Comença amb un sol tema i dades senzilles.','Localitza què coneixes i què busques. Escriu la relació, substitueix les dades i comprova si el resultat és raonable. Usa el dibuix en les palanques.','Una resposta amb unitats i una comprovació: si dobles una dada, què esperes que passi?','Braç|Distància del fulcre a la línia d’acció de la força, perpendicular a la força.;Tensió|Es mesura en volts (V).;Rendiment|Percentatge de l’energia d’entrada que és útil.'],
 materials:['Tria un material per a una necessitat','Compara propietats observables, densitat i ús. Una propietat favorable no resol tots els requisits.','Per a un cable: el nucli ha de conduir i la coberta ha d’aïllar. Localitza dos candidats i explica quina part faria cadascun.','Una elecció amb dues propietats i una limitació.','Densitat|Massa d’un volum de material: per al mateix volum, més densitat implica més massa.;Conductor|Material que deixa passar fàcilment el corrent.;Aïllant|Material que dificulta el pas del corrent.'],
 logic:['De les condicions a les portes lògiques','ESO: relaciona AND, OR i NOT amb situacions quotidianes i taules de dues entrades.','A és «botó premut» i B és «porta tancada». El motor només s’activa si es compleixen totes dues condicions: A & B. Prediu els quatre casos i comprova’ls.','Taula de quatre combinacions i una explicació de per què AND i OR donen resultats diferents.','Bit|Valor 0 o 1.;AND (&)|La sortida és 1 si totes dues entrades són 1.;OR (|)|La sortida és 1 si almenys una entrada és 1.;NOT (!)|Inverteix 0 i 1.'],
 signals:['Diferencia la informació del senyal que la transporta','ESO: observa una ona, compara un senyal continu amb nivells que representen bits i investiga què passa amb les interferències.','Compara el canal sense soroll amb el mateix canal amb soroll. Mantén el missatge i modifica només una variable. Observa l’ona rebuda abans de comptar errors.','Dues proves del mateix missatge, la variable canviada i els errors observats.','Amplitud|Alçada de l’ona respecte del nivell zero.;Freqüència|Nombre de cicles cada segon, en Hz.;Interferència|Un altre senyal que se suma al que vols rebre.;Llindar|Valor amb què el receptor decideix entre 0 i 1.'],
 digitization:['Converteix una ona en una llista de valors','ESO: diferencia quan mesures (mostres/s) de quants valors pots representar (bits/mostra).','Observa els punts blaus. Augmenta les mostres/s sense canviar els bits. Després mantén les mostres i augmenta només els bits. No són el mateix canvi.','Dues comparacions en què només canvies una variable i una explicació del que millora.','Mostreig|Prendre mesures en instants separats.;Quantificació|Aproximar cada mesura a un dels nivells disponibles.;Bit|Amb 1 bit hi ha 2 codis; amb 2 bits, 4.'],
 encoding:['Descobreix com es representen lletres i imatges','ESO: compta bits i bytes, compara A i À i pinta una imatge petita amb diferents nivells de gris.','Codifica A i anota els bytes; repeteix amb À. Després tria Imatge, canvia d’1 a 2 bits per píxel i observa els grisos i la mida.','Mida de dos textos o de dues imatges i una relació entre qualitat i quantitat de dades.','Byte|Grup de 8 bits.;UTF-8|Regla per representar text amb bytes; no totes les lletres ocupen el mateix.;Píxel|Cada punt de la imatge.;Codificar|Representar informació seguint una regla; no significa xifrar-la.'],
 errors:['Comprova si el missatge s’ha alterat','ESO: compta els uns i experimenta amb la paritat abans de treballar amb sumes de comprovació.','Afegeix paritat parella. Canvia un bit i compta els uns. Recupera l’original, canvia dos bits i compara què diu el receptor amb el que saps com a observador.','Un error detectat i un que passi desapercebut, amb el recompte que ho explica.','Paritat parella|S’afegeix un bit perquè el total d’uns sigui parell.;Redundància|Informació addicional per comprovar o recuperar dades.;Detectar|Saber que alguna cosa no encaixa; no necessàriament saber corregir-la.'],
 packets:['Envia un missatge a trossos i torna’l a ordenar','ESO: identifica els paquets pel número, observa l’ordre d’arribada i prova els reenviaments.','Simula sense reintents. Anota els paquets que falten. Repeteix amb el mateix patró i tres reintents; compara la reconstrucció i els bits enviats.','Llista de paquets que falten en dues proves i explicació del cost de reenviar.','Paquet|Fragment de dades amb informació que ajuda a identificar-lo.;Reintent|Tornar a enviar un paquet que no s’ha confirmat.;ACK|Confirmació de recepció.;Patró|Permet repetir el mateix experiment del canal.']
 };
 const advanced={logic:['Demostra equivalències i simplifica','Compara expressions amb fins a cinc variables; usa Karnaugh amb dues a quatre. Justifica agrupacions i busca contraexemples.','Expressió inicial, proposta equivalent i justificació de cada simplificació.'],signals:['Quantifica el comportament del canal','Compara atenuació, soroll, interferència i llindar amb patrons repetibles; argumenta els límits d’una prova sense errors.','Valors del canal i taxa d’errors en almenys tres patrons.'],digitization:['Relaciona mostreig, precisió i pressupost de bits','Investiga aliasing, fase i quantificació. Per a una sinusoide, prova mostres/s per sobre del doble de la freqüència i quantifica mida i error.','Dues configuracions justificades dins del mateix pressupost de bits.'],encoding:['Relaciona Unicode, bytes i representació d’imatges','Compara punts de codi i seqüències UTF-8, detecta seqüències invàlides i calcula la mida d’imatges sense compressió.','Comparació de dues representacions i justificació de la mida en bits.'],errors:['Analitza cobertura i cost de la detecció','Compara paritat i suma mòdul 256, construeix col·lisions i distingeix la decisió del receptor de la veritat de l’observador.','Un contraexemple per a cada mètode i els bits de control afegits.'],packets:['Dissenya una transmissió fiable amb restriccions','Compara mida de paquet, redundància i reintents; avalua la proposta en tres patrons amb límits de bits i temps.','Resultats dels tres patrons i comparació raonada de dues estratègies.']};
 if(!content[kind])return;
 const block=document.createElement('section');block.className='learning-route';block.setAttribute('aria-label','Guia del curs');
 if(['drawings','mechanisms'].includes(kind))document.querySelector('header').after(block);else{const intro=document.querySelector('.intro');if(intro)intro.after(block);else document.querySelector('main').prepend(block)}
 function more(selector,title){const element=document.querySelector(selector);if(!element)return;const details=document.createElement('details');details.className='course-more';details.dataset.courseExtra='';const summary=document.createElement('summary');summary.textContent=title;element.before(details);details.append(summary,element);}
 if(kind==='logic'){more('#karnaughSection','Aprofundiment · mapes de Karnaugh');more('section.details','Aprofundiment · minterms i contraexemples');}
 if(kind==='packets')more('.mission','Repte de síntesi · Batxillerat / ampliació ESO');
 let lastCourse;
 function render(){const c=window.TechEduCurrent(),batx=c.course==='batx'&&advanced[kind],a=content[kind],b=advanced[kind];block.innerHTML='<span class="eyebrow">'+(batx?'BATXILLERAT':'3r D’ESO · INICIACIÓ')+'</span><h2></h2><p class="route-goal"></p><details><summary>Guia de treball i vocabulari</summary><p class="route-start"></p><p><b>Evidència esperada: </b><span class="route-evidence"></span></p><dl></dl></details>';
 block.querySelector('h2').textContent=batx?b[0]:a[0];block.querySelector('.route-goal').textContent=batx?b[1]:a[1];block.querySelector('.route-start').textContent=batx?'Prepara el repte adaptat i anota una predicció abans de mostrar els resultats.':a[2];block.querySelector('.route-evidence').textContent=batx?b[2]:a[3];for(const item of a[4].split(';')){const [term,definition]=item.split('|'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=term;dd.textContent=definition;block.querySelector('dl').append(dt,dd)}block.querySelector('details').open=c.level==='guided'||c.supports.stepByStep;
 if(lastCourse!==c.course){document.querySelectorAll('[data-course-extra]').forEach(e=>e.open=!!batx);lastCourse=c.course;}
 }
 window.addEventListener('techedu-level',render);render();
})();
