import {downloadJSON} from '../../shared/workspace.mjs';
export function setupGallery({getDocument,openDocument,preview,valid,beforeOpen}){
 const P=TechEduProfiles,key='techdrawings.gallery.v1';let owner=null,revision=0,items=[];const dialog=document.createElement('dialog');dialog.id='galleryDialog';dialog.innerHTML='<div class="dialog-head"><h2>Els meus projectes</h2><button id="closeGallery" aria-label="Tanca la galeria">✕</button></div><p>Desa còpies del dibuix actual. Cada compte té la seva galeria local. Exporta una còpia per conservar-la fora del navegador.</p><div class="gallery-actions"><button id="saveProject" class="primary">Desa el dibuix com a projecte</button><button id="exportGallery">Exporta galeria JSON</button><label>Importa galeria<input id="importGallery" type="file" accept=".json,application/json"></label></div><p id="galleryStatus" role="status"></p><div id="galleryItems"></div>';document.body.append(dialog);const $=s=>dialog.querySelector(s),status=t=>$('#galleryStatus').textContent=t;
 function validate(list){if(!Array.isArray(list)||list.length>12)throw Error('La galeria admet fins a 12 projectes.');const seen=new Set();const next=list.map(item=>{if(!item||!valid(item.document)||typeof item.id!=='string'||seen.has(item.id.slice(0,100)))throw Error('Projecte no vàlid o identificador duplicat.');seen.add(item.id.slice(0,100));return {id:item.id.slice(0,100),name:String(item.name||item.document.title).slice(0,100),document:item.document,updatedAt:String(item.updatedAt||'').slice(0,40)}});if(new TextEncoder().encode(JSON.stringify(next)).length>400000)throw Error('La galeria supera 400 kB. Exporta i elimina algun projecte abans de continuar.');return next}
 function read(){return owner?P.readWork(owner,'drawing-gallery'):JSON.parse(localStorage.getItem(key)||'null')}
 function commit(next){try{if((P.active()?.id||null)!==owner)throw Error('El compte ha canviat. Torna a obrir la galeria.');next=validate(next);if((read()?.revision||0)!==revision)throw Error('La galeria ha canviat en una altra pestanya. Torna a obrir-la.');const value={draft:{extra:{projects:next}},history:[],events:[]};if(owner)revision=P.writeWork(owner,'drawing-gallery',value,revision).revision;else{localStorage.setItem(key,JSON.stringify({...value,revision:revision+1}));revision++}items=next;render();status('Galeria desada en aquest navegador.');return true}catch(e){status('No s’ha desat: '+e.message);return false}}
 function render(){const root=$('#galleryItems');root.replaceChildren();items.forEach(item=>{const card=document.createElement('article');card.className='project-card';const img=document.createElement('img');img.alt='Miniatura de '+item.name;img.src='data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(preview(item.document))));card.append(img);const title=document.createElement('h3');title.textContent=item.name;card.append(title);const actions=document.createElement('div');for(const [name,fn] of [
 ['Obre',()=>{if(!beforeOpen())return;if(getDocument().objects.length&&!confirm('Obrir el projecte substituirà l’esborrany actual. Si el vols conservar a la galeria, desa’n abans una còpia.'))return;openDocument(JSON.parse(JSON.stringify(item.document)));dialog.close()}],
 ['Actualitza',()=>{if(!confirm('Substituir aquest projecte pel dibuix actual?'))return;commit(items.map(v=>v.id===item.id?{...v,document:JSON.parse(JSON.stringify(getDocument())),updatedAt:new Date().toISOString()}:v))}],
 ['Reanomena',()=>{const name=prompt('Nom del projecte',item.name);if(name?.trim())commit(items.map(v=>v.id===item.id?{...v,name:name.trim().slice(0,100)}:v))}],
 ['Duplica',()=>commit([...items,{...item,id:crypto.randomUUID(),name:(item.name+' · còpia').slice(0,100)}])],
 ['Elimina',()=>{if(confirm('Eliminar aquesta còpia de la galeria? El dibuix obert no canviarà.'))commit(items.filter(v=>v.id!==item.id))}]
 ]){const b=document.createElement('button');b.textContent=name;b.onclick=fn;actions.append(b)}card.append(actions);root.append(card)});if(!items.length)root.textContent='Encara no hi ha projectes desats.';}
 $('#closeGallery').onclick=()=>dialog.close();$('#saveProject').onclick=()=>{if(!beforeOpen())return;commit([...items,{id:crypto.randomUUID(),name:getDocument().title,document:JSON.parse(JSON.stringify(getDocument())),updatedAt:new Date().toISOString()}])};$('#exportGallery').onclick=()=>downloadJSON({format:'techedu-gallery',version:1,projects:items},'tecnofigures-galeria.json');
 $('#importGallery').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>450000)throw Error('Fitxer massa gran.');const data=JSON.parse(await file.text(),(k,v)=>{if(['__proto__','constructor','prototype'].includes(k))throw Error('Clau no admesa.');return v});if(data.format!=='techedu-gallery'||data.version!==1)throw Error('Format no reconegut.');const next=validate(data.projects);if(confirm('La importació substituirà aquesta galeria. Has exportat els projectes que vols conservar?'))commit(next)}catch(e){status(e.message)}finally{e.target.value=''}};
 window.addEventListener('techedu-level',()=>{if((P.active()?.id||null)!==owner){dialog.close();items=[];$('#galleryItems').replaceChildren()}});
 return ()=>{owner=P.active()?.id||null;items=[];revision=0;render();try{const record=read();revision=record?.revision||0;items=validate(record?.draft?.extra?.projects||[]);render();status(`${items.length}/12 projectes · ${owner?'compte actiu':'Visitant'}`);dialog.showModal()}catch(e){status('No es pot llegir la galeria: '+e.message);dialog.showModal()}};
}
