const limit=(v,d,min,max)=>Number.isFinite(Number(v))?Math.max(min,Math.min(max,Number(v))):d;
export function inclineGeometry(o){const legacy=o.rampAngle===undefined&&o.rampLength===undefined&&o.rampObject===undefined,angle=limit(o.rampAngle,legacy?Math.atan2(250,550)*180/Math.PI:30,5,70),L=limit(o.rampLength,legacy?Math.hypot(550,250):500,180,650),a=angle*Math.PI/180,c=Math.cos(a),s=Math.sin(a),size=limit(o.objectSize,65,25,110),position=limit(o.objectPosition,.55,Math.max(.15,size/(2*L)),Math.min(.85,1-size/(2*L))),x=Number(o.x)||0,y=Number(o.y)||0;return {legacy,angle,L,a,c,s,size,position,x,y,base:y+L*s,px:x+L*c*position,py:y+L*s*(1-position)}}
export function renderIncline(o,label,color){const g=inclineGeometry(o),{x,y,L,base,c,s,size,px,py,angle}=g;const stroke=`stroke="${color}" stroke-width="3" stroke-linejoin="round"`;let out=`<path d="M${x} ${base} L${x+L*c} ${y} V${base} Z" ${stroke} fill="#edf3f1"/>`;
 if(o.roughSurface)out+=Array.from({length:21},(_,i)=>{const d=i*L/20;return `<path d="M${x+d*c} ${base-d*s} l${s*9-c*7} ${c*9+s*7}" ${stroke}/>`}).join('');
 const cx=px-s*size/2,cy=py-c*size/2,type=['block','ball','cart','none'].includes(o.rampObject)?o.rampObject:(g.legacy?'none':'block');
 if(type!=='none'){
  const graphic=type==='ball'?`<circle cx="0" cy="${-size/2}" r="${size/2}" ${stroke} fill="white"/>`:`<rect x="${-size/2}" y="${-size}" width="${size}" height="${type==='cart'?size-12:size}" rx="3" ${stroke} fill="white"/>`+(type==='cart'?`<circle cx="${-size*.3}" cy="-8" r="8" ${stroke} fill="white"/><circle cx="${size*.3}" cy="-8" r="8" ${stroke} fill="white"/>`:'');
  out+=`<g transform="translate(${px} ${py}) rotate(${-angle})">${graphic}</g>`;
 }
 const objectLabel=label(cx,cy+5,type==='none'?'':o.objectLabel??'m',19,'middle',color);
 const theta=label(x+60,base-12,o.showAngle===false||g.legacy?'':o.angleLabel||Number(angle.toFixed(1))+'°',18,'middle',color);
 if(o.showAngle!==false&&!g.legacy)out+=`<path d="M${x+42} ${base} A42 42 0 0 0 ${x+42*c} ${base-42*s}" ${stroke} fill="none"/>`;
 const vector=(dx,dy,name,enabled)=>{let drawn='';if(enabled&&type!=='none'){const a=Math.atan2(dy,dx)*180/Math.PI,len=Math.hypot(dx,dy);drawn=`<g transform="translate(${cx} ${cy}) rotate(${a})" stroke="#c7552c" stroke-width="3" fill="none"><path d="M0 0 H${len} M${len-10} -6 L${len} 0 L${len-10} 6"/></g>`;}return drawn+label(cx+dx*1.15,cy+dy*1.15+5,enabled&&type!=='none'?name:'',17,'middle','#a44020');};
 out+=objectLabel+theta+vector(0,100,'P',o.rampWeight===true)+vector(-s*100,-c*100,'N',o.rampNormal===true);
 const friction=o.rampFriction||'none',force=o.rampForce||'none';out+=vector(c*100*(friction==='down'?-1:1),-s*100*(friction==='down'?-1:1),'Fr',friction!=='none')+vector(c*150*(force==='down'?-1:1),-s*150*(force==='down'?-1:1),'F',force!=='none');
 return out+label(x+L*c/2,base+55,o.label||'Pla inclinat',20,'middle',color);
}
export function inclineFields(o,field){if(o.kind!=='ramp')return '';const g=inclineGeometry(o),check=(k,n,yes)=>`<label>${n}<input type="checkbox" data-property="${k}" ${yes?'checked':''}></label>`,select=(k,n,values,current)=>`<label>${n}<select data-property="${k}">${values.map(([v,t])=>`<option value="${v}" ${v===current?'selected':''}>${t}</option>`).join('')}</select></label>`;return field('rampAngle','Angle (°)','number',g.angle)+field('rampLength','Longitud del pendent (px)','number',g.L)+check('showAngle','Mostra l’angle',o.showAngle!==false&&!g.legacy)+field('angleLabel','Etiqueta de l’angle (buit = valor)','text',o.angleLabel||'')+check('roughSurface','Superfície rugosa',o.roughSurface)+select('rampObject','Objecte',[['block','Bloc'],['ball','Bola'],['cart','Carretó'],['none','Sense objecte']],o.rampObject||(g.legacy?'none':'block'))+field('objectLabel','Etiqueta de l’objecte','text',o.objectLabel??'m')+field('objectSize','Mida de l’objecte (px)','number',g.size)+field('objectPosition','Posició al pendent (0,15–0,85)','number',g.position)+check('rampWeight','Mostra el pes P',o.rampWeight)+check('rampNormal','Mostra la normal N',o.rampNormal)+select('rampFriction','Fregament',[['none','Ocult'],['up','Cap amunt del pendent'],['down','Cap avall del pendent']],o.rampFriction||'none')+select('rampForce','Força aplicada',[['none','Oculta'],['up','Cap amunt del pendent'],['down','Cap avall del pendent']],o.rampForce||'none')+'<p class="muted">Vectors esquemàtics de longitud independent del valor físic. El sentit del fregament s’escull segons la situació; no es calcula l’equilibri.</p>';}

export function upgradeRamp(o){const g=inclineGeometry(o);if(g.legacy)Object.assign(o,{rampAngle:g.angle,rampLength:g.L,rampObject:'none',showAngle:false});}
