(function(){
 const $=id=>document.getElementById(id),D=DigitalCore;
 const gradient=()=>Array.from({length:64},(_,i)=>Math.round((i%8)*255/7));
 let image=gradient(),encoded=null,decodedRequested=false;
 const tasks={guided:{title:'Una lletra no sempre ocupa un byte',text:'Compara A i À. Escriu cada lletra per separat i mira quants bytes necessita. Després tria la imatge i compara 1 i 2 bits per píxel.',steps:['Prepara el repte: envia A.','Anota el nombre de bytes.','Canvia A per À i compara.','Tria Imatge i compara 1 i 2 bits per píxel.']},standard:{title:'Canviar un bit pot canviar el missatge',text:'Codifica «Hola, Àngel!». Inverteix un bit, llegeix els bytes i comprova si el text canvia o deixa de ser UTF-8 vàlid. Després compara la mida de la imatge amb 2 i 8 bits per píxel.',steps:['Prepara el repte i mostra els codis.','Tria una posició i inverteix només aquell bit.','Llegeix els bytes; anota el canvi o l’error.','Recupera els originals i prova una altra posició.']},extension:{title:'El mateix aspecte, codis diferents',text:'Compara «é» amb «é»: visualment s’assemblen, però el segon combina una e amb un accent. Compara punts de codi i bytes sense normalitzar-los. A la imatge, limita les dades a 128 bits i justifica quins grisos perds.',steps:['Prepara el text amb les dues formes d’é separades per un espai.','Inspecciona la taula de punts de codi i bytes.','Prova al canal un byte d’una lletra accentuada.','Tria Imatge: 64 píxels × bits/píxel ≤ 128. Compara amb l’original.']}};
 function adapt(){const {level='standard',supports={}}=window.TechEduCurrent?.()||{},t=tasks[level];$('activityTitle').textContent=t.title;$('activityText').textContent=supports.shortText?t.steps.slice(0,2).join(' '):t.text;$('activitySteps').replaceChildren(...t.steps.map(text=>{const li=document.createElement('li');li.textContent=text;return li}));$('activitySteps').hidden=!$('showSteps').checked;}
 function decode(){
  $('decodeError').hidden=true;
  if(!decodedRequested){$('decodedText').textContent='';$('decodeStatus').textContent='Prem «Llegeix els bytes» per descodificar la seqüència.';return;}
  try{const text=D.decodeText($('receivedBits').value),bytes=D.parseBinary($('receivedBits').value);$('decodedText').textContent=text||'(missatge buit)';const original=encoded?.bytes||[];let changes=0;if(bytes.length===original.length)for(let i=0;i<bytes.length;i++){let xor=bytes[i]^original[i];while(xor){changes+=xor&1;xor>>>=1;}}
   $('decodeStatus').textContent='UTF-8 vàlid. '+(bytes.length===original.length?changes+' bits diferents respecte de l’original.':'La longitud en bytes és diferent de l’original.')+(text===$('message').value?' El text coincideix.':' El text ha canviat.');
  }catch(e){$('decodedText').textContent='';$('decodeStatus').textContent='No s’ha pogut descodificar: '+e.message;}
 }
 function byteLink(){const bytes=encoded?.bytes||[],index=Number($('byteChoice').value);const valid=Number.isInteger(index)&&index>=0&&index<bytes.length;$('sendByte').hidden=!valid;if(valid)$('sendByte').href='./#bits='+bytes[index].toString(2).padStart(8,'0');}
 function textRender(){
  try{encoded=D.encodeText($('message').value);$('textMetrics').innerHTML=[[encoded.symbols.length,'punts de codi Unicode'],[encoded.bytes.length,'bytes UTF-8'],[encoded.bits,'bits de dades']].map(([n,label])=>`<div class="metric"><b>${n}</b><span>${label}</span></div>`).join('');
   $('symbolRows').replaceChildren(...encoded.symbols.map(s=>{const tr=document.createElement('tr');for(const value of [(s.char===' '?'␠':s.char==='\n'?'↵':s.char)+' · U+'+s.char.codePointAt(0).toString(16).toUpperCase(),s.bytes.join(' '),s.bytes.map(b=>b.toString(2).padStart(8,'0')).join(' ')]){const td=document.createElement('td');td.textContent=value;tr.append(td);}return tr;}));
   const old=$('byteChoice').value;$('byteChoice').replaceChildren(...encoded.bytes.map((b,i)=>{const o=document.createElement('option');o.value=i;o.textContent='Byte '+(i+1)+' · '+b.toString(2).padStart(8,'0');return o}));$('byteChoice').value=old!==''&&Number(old)>=0&&Number(old)<encoded.bytes.length?old:'0';$('bitToFlip').max=Math.max(1,encoded.bits);byteLink();
  }catch(e){encoded=null;$('textMetrics').replaceChildren();$('symbolRows').replaceChildren();$('byteChoice').replaceChildren();$('sendByte').hidden=true;$('decodeError').textContent=e.message;$('decodeError').hidden=false;return;}
  decode();const visible=$('reveal').checked;$('textMeasures').hidden=!visible;$('decodedResults').hidden=!visible;$('receivedBits').parentElement.hidden=!visible;document.querySelectorAll('#textPanel .byte-tools').forEach(e=>e.hidden=!visible);
 }
 function pixelRender(){
  $('brushValue').textContent=$('brush').value+' / 255';const r=D.pixels(image,Number($('pixelDepth').value));
  [...$('pixelOriginal').children].forEach((el,i)=>{el.style.backgroundColor=`rgb(${image[i]},${image[i]},${image[i]})`;el.setAttribute('aria-label',`Fila ${Math.floor(i/8)+1}, columna ${i%8+1}: gris ${image[i]}. Pinta amb ${$('brush').value}.`)});
  [...$('pixelDecoded').children].forEach((el,i)=>{el.style.backgroundColor=`rgb(${r.decoded[i]},${r.decoded[i]},${r.decoded[i]})`;el.title=`Píxel ${i+1}: codi ${r.codes[i]}, gris ${r.decoded[i]}`;});
  $('pixelMetrics').innerHTML=[[r.levels,'nivells de gris'],[r.bits+' bits','64 píxels × bits/píxel'],[r.bits/8+' bytes','dades sense capçalera']].map(([n,label])=>`<div class="metric"><b>${n}</b><span>${label}</span></div>`).join('');$('pixelStream').value=r.binary;$('pixelMeasures').hidden=!$('revealImage').checked;
 }
 function render(){const isText=$('encodingMode').value==='text';$('textPanel').hidden=!isText;$('imagePanel').hidden=isText;textRender();pixelRender();}
 function resetText(){try{$('receivedBits').value=D.encodeText($('message').value).binary;decodedRequested=false;}catch{}textRender();}
 for(let i=0;i<64;i++){const b=document.createElement('button');b.type='button';b.dataset.pixel=i;$('pixelOriginal').append(b);$('pixelDecoded').append(document.createElement('span'));}
 $('pixelOriginal').onclick=e=>{const b=e.target.closest('[data-pixel]');if(!b)return;image[Number(b.dataset.pixel)]=Number($('brush').value);pixelRender();};
 $('message').oninput=resetText;$('receivedBits').oninput=()=>{decodedRequested=false;decode()};$('encodingMode').onchange=render;$('pixelDepth').onchange=pixelRender;$('brush').oninput=pixelRender;$('reveal').onchange=textRender;$('revealImage').onchange=pixelRender;$('showSteps').onchange=adapt;$('byteChoice').onchange=byteLink;
 $('decodeText').onclick=()=>{decodedRequested=true;decode()};$('restoreText').onclick=resetText;
 $('flipBit').onclick=()=>{try{$('receivedBits').value=D.flip($('receivedBits').value,Number($('bitToFlip').value));decodedRequested=true;decode()}catch(e){$('decodeError').textContent=e.message;$('decodeError').hidden=false;}};
 function replaceImage(values){if(window.TechEduSession?.archive()===false)return;image=values;pixelRender();}
 $('gradient').onclick=()=>replaceImage(gradient());$('checker').onclick=()=>replaceImage(Array.from({length:64},(_,i)=>(Math.floor(i/8)+i%8)%2*255));
 $('loadChallenge').onclick=()=>{if(window.TechEduSession?.archive()===false)return;const {level,supports}=window.TechEduCurrent();$('encodingMode').value='text';$('message').value={guided:'A',standard:'Hola, Àngel!',extension:'é é'}[level];image=gradient();$('pixelDepth').value='2';$('showSteps').checked=level==='guided'||supports.stepByStep;$('reveal').checked=$('revealImage').checked=!(level==='guided'||supports.hideSolution);$('codingPrediction').value='';$('predictionFeedback').textContent='';resetText();adapt();render();};
 $('checkPrediction').onclick=()=>{$('predictionFeedback').textContent=!$('codingPrediction').value?'Tria una resposta.':$('codingPrediction').value==='4'?'Correcte: 00, 01, 10 i 11 són quatre codis, per a quatre grisos.':'Escriu totes les combinacions de dos bits: 00, 01, 10 i 11. Hi ha quatre nivells.';};
 window.TechEduActivity={afterRestore:render,capture:()=>({pixels:image,decoded:decodedRequested,label:$('encodingMode').value==='text'?'Text UTF-8':'Imatge · '+$('pixelDepth').value+' bits/píxel'}),restore:extra=>{image=gradient();if(extra?.pixels){try{D.pixels(extra.pixels,8);image=[...extra.pixels]}catch{}}decodedRequested=extra?.decoded===true;adapt();render();},activate:({restored})=>{const {level,supports}=window.TechEduCurrent();if(!restored){$('showSteps').checked=level==='guided'||supports.stepByStep;$('reveal').checked=$('revealImage').checked=!(level==='guided'||supports.hideSolution);}adapt();render();$('workPrediction').parentElement.firstChild.textContent='Predicció: A i À ocuparan els mateixos bytes? Quants grisos hi haurà amb 2 bits per píxel? Tria un dels dos casos i justifica la resposta.';$('workConclusion').parentElement.firstChild.textContent='Evidència: copia el nombre de bytes dels dos textos o els bits totals de les dues imatges. Explica quin canvi has observat en descodificar.';}};
 window.addEventListener('techedu-level',adapt);resetText();adapt();render();
})();
