(function(){
 const $=id=>document.getElementById(id),R=ReliabilityCore;
 let source=null;let incoming=new URLSearchParams(location.hash.slice(1)).get('payload');if(!/^[01]{8,64}$/.test(incoming||'')||incoming.length%8)incoming=null;
 const tasks={guided:{title:'Un bit canvia: la paritat ho veu?',text:'Amb paritat parella, inverteix només el primer bit de dades. Compta els uns rebuts i comprova si encara són parells.',steps:['Prepara el repte.','Prediu si un únic canvi altera la paritat.','Inverteix un bit de dades.','Mostra la comprovació i compta els uns.']},standard:{title:'Dos canvis, dos mètodes',text:'Prova els casos d’un bit i de dos bits. Compara la paritat amb la suma de comprovació, anotant els bits addicionals de cada mètode.',steps:['Prepara la paritat i prova dos bits alterats.','Compara la comprovació amb la veritat de l’observador.','Canvia a suma de comprovació i repeteix.','Desa una evidència de cada mètode.']},extension:{title:'Una comprovació correcta amb dades incorrectes',text:'Construeix dos bytes diferents dels originals que mantinguin la mateixa suma mòdul 256. Justifica per què el receptor no detecta el canvi i compara el cost amb la paritat.',steps:['Prepara la suma amb els bytes 65 i 66.','Resta 1 al primer byte i suma 1 al segon.','Compara la suma rebuda amb el control.','Mostra l’original i explica la col·lisió.']}};
 const esoTasks={"guided": {"title": "Compta els uns abans i després", "text": "Amb paritat parella, canvia un sol bit i torna a comptar els uns. El total continua sent parell?", "steps": ["Prepara el repte.", "Mostra la comprovació i compta els uns.", "Inverteix un bit.", "Compara el nou recompte."]}, "standard": {"title": "Un canvi es veu; dos poden passar desapercebuts", "text": "Prova primer un bit alterat i després dos, sempre amb paritat. Compara la decisió del receptor i la comprovació amb l’original.", "steps": ["Prepara paritat.", "Prova el cas d’un bit.", "Prova el cas de dos bits.", "Explica per què el nombre d’uns torna a tenir la mateixa paritat."]}, "extension": {"title": "Demostra el límit de la paritat", "text": "Troba dues alteracions diferents de dos bits que el receptor accepti. La informació és correcta només perquè ha superat la comprovació?", "steps": ["Prepara la paritat.", "Inverteix dos bits i mostra la comprovació.", "Recupera l’original i prova altres dos bits.", "Anota les dades alterades i justifica el resultat."]}};
 function adapt(){const {level='standard',supports={}}=window.TechEduCurrent?.()||{},t=(window.TechEduCurrent?.().course==='batx'?tasks:esoTasks)[level];$('activityTitle').textContent=t.title;$('activityText').textContent=supports.shortText?t.steps.slice(0,2).join(' '):t.text;$('activitySteps').replaceChildren(...t.steps.map(text=>{const e=document.createElement('li');e.textContent=text;return e}));$('activitySteps').hidden=!$('showSteps').checked;}
 function frameGrid(id,bits,interactive){const root=$(id);root.replaceChildren(...[...bits].map((b,i)=>{const el=document.createElement(interactive?'button':'span');el.textContent=b;if(i>=source.payload.length)el.classList.add('control-bit');if(interactive){el.type='button';el.dataset.bit=i;el.setAttribute('aria-label',`Bit ${i+1}${i>=source.payload.length?' de control':''}: ${b}. Inverteix.`);if($('showTruth').checked&&source.frame[i]!==b)el.classList.add('changed');}return el}));}
 function render(){
  $('frameError').hidden=true;$('receiverResult').hidden=!$('reveal').checked;$('observerResult').hidden=!$('showTruth').checked;
  try{source=R.protect($('payload').value,$('method').value);if(source.payload.length>64)throw Error('En aquest laboratori, utilitza com a màxim 8 bytes.');document.querySelector('[data-case="control"]').disabled=source.overhead===0;frameGrid('sentFrame',source.frame,false);const bits=R.binary($('received').value);if(bits.length>72)throw Error('Trama massa llarga.');frameGrid('receivedFrame',bits,true);
   $('costMetrics').replaceChildren();for(const text of [`Dades: ${source.payload.length} bits.`,`Control: ${source.overhead} bits addicionals.`,`Trama completa: ${source.frame.length} bits.`]){const p=document.createElement('p');p.textContent=text;$('costMetrics').append(p);}
   const v=R.verify(bits,$('method').value);if(bits.length!==source.frame.length)throw Error('La trama rebuda ha de mantenir la longitud de l’enviada.');
   $('receiverVerdict').className='receiver-verdict'+(v.passed===false?' bad':v.passed===null?' unknown':'');$('receiverVerdict').textContent=v.passed===null?'Sense protecció: no es pot comprovar la integritat.':v.passed?'Comprovació superada. No s’ha detectat cap error.':'Error detectat. Cal rebutjar o demanar un reenviament.';
   $('receiverCalculation').textContent=$('method').value==='parity'?`La trama rebuda té ${v.ones} uns: ${v.ones%2?'senar':'parell'}. La paritat acordada és parella.`:$('method').value==='checksum'?`Suma dels bytes de dades rebuts mòdul 256: ${v.sum}. Control rebut: ${parseInt(v.received,2)}. Només es comparen aquests dos valors.`:'No s’ha transmès cap bit de comprovació.';
   const truth=R.observe(source.frame,bits),dataSame=v.payload===source.payload;$('observerVerdict').textContent=`${truth.changes} bits de la trama alterats. Les dades ${dataSame?'coincideixen amb':'són diferents de'} les originals. `+(v.passed===true&&!dataSame?'Aquest error ha passat desapercebut.':truth.same?'No hi ha cap alteració.':v.passed===false?'El receptor ha detectat una alteració.':'El receptor no pot assegurar la integritat.');
  }catch(e){$('frameError').textContent=e.message;$('frameError').hidden=false;$('receiverResult').hidden=true;$('observerResult').hidden=true;$('receiverVerdict').textContent='';}
 }
 function reset(){try{$('received').value=R.protect($('payload').value,$('method').value).frame;}catch{}render();}
 function prepare(which){if(window.TechEduSession?.archive()===false)return false;$('payload').value='01000001 01000010';if(which==='collision')$('method').value='checksum';reset();const indices={single:[7],double:[6,7],collision:[7,15],control:[source.frame.length-1],clean:[]}[which];$('received').value=R.flip(source.frame,indices);render();}
 document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>prepare(b.dataset.case));$('receivedFrame').onclick=e=>{const b=e.target.closest('[data-bit]');if(!b)return;try{const index=Number(b.dataset.bit);$('received').value=R.flip($('received').value,[index]);render();$('receivedFrame').querySelector('[data-bit="'+index+'"]')?.focus()}catch{}};
 $('payload').oninput=reset;$('method').onchange=reset;$('received').oninput=render;$('resetFrame').onclick=reset;$('reveal').onchange=render;$('showTruth').onchange=render;$('showSteps').onchange=adapt;
 $('loadChallenge').onclick=()=>{if(window.TechEduSession?.archive()===false)return;const {level,supports}=window.TechEduCurrent();$('method').value=level==='extension'&&window.TechEduCurrent().course==='batx'?'checksum':'parity';$('payload').value='01000001 01000010';$('showSteps').checked=level==='guided'||supports.stepByStep;$('reveal').checked=!(level==='guided'||supports.hideSolution);$('showTruth').checked=false;$('prediction').value='';$('predictionFeedback').textContent='';reset();adapt();};
 $('checkPrediction').onclick=()=>{$('predictionFeedback').textContent=!$('prediction').value?'Tria una resposta.':$('prediction').value==='no'?'Correcte. Dues inversions conserven la paritat, encara que canviïn les dades.':'Compta els uns després de dues inversions: el total continua tenint la mateixa paritat.';};
 window.TechEduActivity={capture:()=>({label:$('method').selectedOptions[0]?.textContent||'Errors'}),afterRestore:render,restore:()=>{adapt();render()},activate:({restored})=>{const {level,supports}=window.TechEduCurrent();if(!restored){$('showSteps').checked=level==='guided'||supports.stepByStep;$('reveal').checked=!(level==='guided'||supports.hideSolution);$('showTruth').checked=false;}if(incoming){const data=incoming;incoming=null;if(window.TechEduSession?.archive()!==false){$('payload').value=data;reset();window.TechEduSession?.save('byte importat');}}adapt();render();$('workPrediction').parentElement.firstChild.textContent='Predicció: la paritat detectarà un canvi? I dos? Tria un cas abans d’invertir els bits.';$('workConclusion').parentElement.firstChild.textContent='Evidència: anota les dades i el control rebuts, la decisió del receptor i si realment hi havia alteracions.';}};
 window.addEventListener('techedu-level',adapt);reset();adapt();
})();
