(function(){
 const $=id=>document.getElementById(id),R=ReliabilityCore,keys=['message','packetSize','method','retries','loss','corruption','jitter','bitRate','seed'];
 let ran=false,result=null,missionDone=false;const read=()=>Object.fromEntries(keys.map(k=>[k,$(k).value])),set=c=>{for(const [k,v] of Object.entries(c))if(keys.includes(k))$(k).value=v},fmt=n=>Number(n).toLocaleString('ca',{maximumFractionDigits:1});
 const mission={message:'Hola, món!',loss:25,corruption:20,jitter:200,bitRate:512,seed:42};
 const tasks={guided:{title:'Troba el paquet que falta',text:'Envia amb 40% de pèrdues i sense reintents. Mira quins números falten. Mantén el mateix patró, permet tres reintents i comprova si es recuperen.',steps:['Prepara l’activitat i simula.','Anota els números dels paquets que falten.','Canvia només els reintents de 0 a 3.','Simula de nou i compara els bits totals.']},standard:{title:'Arribar complet no sempre és arribar bé',text:'Compara el mateix canal amb i sense protecció. Observa quins paquets es rebutgen, quins es reenvien i quin text es reconstrueix. Després comprova’l com a observador.',steps:['Prepara l’activitat sense protecció.','Simula i desa una evidència.','Activa la suma de comprovació mantenint el patró.','Compara decisions, reconstrucció i cost.']},extension:{title:'Fiabilitat amb un límit de dades i temps',text:'Resol el repte final amb una combinació de mida de paquet, protecció i reintents. Compara almenys dues estratègies en els mateixos tres patrons.',steps:['Carrega les condicions del repte final.','Tria mida, protecció i reintents.','Avalua els tres patrons i desa l’evidència.','Compara una altra estratègia i justifica el cost.']}};
 function adapt(){const {level='standard',supports={}}=window.TechEduCurrent?.()||{},t=tasks[level];$('activityTitle').textContent=t.title;$('activityText').textContent=supports.shortText?t.steps.slice(0,2).join(' '):t.text;$('activitySteps').replaceChildren(...t.steps.map(text=>{const li=document.createElement('li');li.textContent=text;return li}));$('activitySteps').hidden=!$('showSteps').checked;}
 function badges(id,items){$(id).replaceChildren(...items.map(({text,missing})=>{const e=document.createElement('span');e.textContent=text;if(missing)e.className='missing';return e}));}
 function render(){
  $('packetResults').hidden=!ran||!result||!$('reveal').checked;$('truthResult').hidden=!ran||!result||!$('showTruth').checked;
  if(!ran||!result)return;
  $('packetMetrics').innerHTML=[[result.received.length+'/'+result.blocks.length,'paquets reconstruïts'],[result.totalBits+' bits','cost total'],[fmt(result.timeMs)+' ms','temps total']].map(([v,label])=>`<div class="metric"><b>${v}</b><span>${label}</span></div>`).join('');
  badges('arrivalOrder',result.events.filter(e=>e.status==='accepted').map(e=>({text:'P'+(e.seq+1)})));
  badges('assembledOrder',result.blocks.map((_,i)=>({text:'P'+(i+1)+(result.missing.includes(i)?' · falta':''),missing:result.missing.includes(i)})));
  $('receiverSummary').textContent=result.complete?'Han arribat tots els paquets esperats. S’ordenen pel número de seqüència.':'Falten paquets: no es pot reconstruir el missatge complet.';
  $('reconstructed').textContent=!result.complete?'Missatge incomplet.':result.utf8Valid===false?'Els bytes reconstruïts no formen un text UTF-8 vàlid.':result.text;
  $('packetRows').innerHTML=result.events.map(e=>`<tr><td>P${e.seq+1}</td><td>${e.round+1}</td><td>${fmt(e.start)}</td><td>${e.arrival===null?'—':fmt(e.arrival)}</td><td>${{lost:'Sense confirmació · perdut',rejected:'Rebutjat · error detectat',accepted:'Acceptat'}[e.status]}</td></tr>`).join('');
  $('truthResult').textContent=result.identical?'Observador: el missatge reconstruït coincideix exactament amb l’original.':result.complete?'Observador: el missatge s’ha completat, però les dades han canviat. Hi ha hagut errors no detectats.':'Observador: la transmissió no s’ha completat.';
 }
 function simulate(){try{result=R.packets(read());ran=true;$('packetError').hidden=true;$('simulationStatus').textContent='Transmissió calculada. Revisa l’ordre, les decisions i el cost.';}catch(e){ran=false;result=null;$('packetError').textContent=e.message;$('packetError').hidden=false;$('simulationStatus').textContent='Corregeix la configuració abans de simular.';}render();}
 function evaluate(){try{const m=R.challenge(read());$('missionResult').textContent=(m.passed?'Repte superat en els tres patrons.':'Repte encara no superat.')+'\n'+m.runs.map(r=>`Patró ${r.config.seed}: ${r.identical?'missatge correcte':'missatge incorrecte o incomplet'} · ${r.totalBits}/900 bits · ${fmt(r.timeMs)}/5.000 ms`).join('\n');missionDone=true;}catch(e){$('missionResult').textContent=e.message;missionDone=false;}}
 function invalidate(){ran=false;result=null;missionDone=false;$('missionResult').textContent='';$('packetError').hidden=true;$('simulationStatus').textContent='Configuració modificada. Torna a simular.';render();}
 for(const key of keys){$(key).addEventListener('input',invalidate);$(key).addEventListener('change',invalidate);}
 $('simulate').onclick=simulate;$('reveal').onchange=render;$('showTruth').onchange=render;$('showSteps').onchange=adapt;
 $('prepareMission').onclick=()=>{if(window.TechEduSession?.archive()===false)return;set(mission);invalidate();};
 $('evaluateMission').onclick=()=>{set(mission);simulate();evaluate();};
 $('loadChallenge').onclick=()=>{if(window.TechEduSession?.archive()===false)return;const {level,supports}=window.TechEduCurrent();set({...mission,packetSize:3,method:level==='standard'?'none':'checksum',retries:level==='guided'?0:2,loss:level==='guided'?40:25});$('showSteps').checked=level==='guided'||supports.stepByStep;$('reveal').checked=!(level==='guided'||supports.hideSolution);$('showTruth').checked=false;$('prediction').value='';$('predictionFeedback').textContent='';invalidate();adapt();};
 $('checkPrediction').onclick=()=>{$('predictionFeedback').textContent=!$('prediction').value?'Tria una resposta.':$('prediction').value==='no'?'Correcte. La comprovació no conté totes les dades. Per recuperar un paquet perdut, aquí cal demanar un reenviament.':'La suma permet comprovar dades rebudes; no reconstrueix un paquet que no ha arribat.';};
 window.TechEduActivity={capture:()=>({ran,missionDone,label:missionDone?'Repte final · '+$('method').value:'Paquets de '+$('packetSize').value+' bytes · '+$('retries').value+' reintents'}),restore:extra=>{ran=extra?.ran===true;missionDone=extra?.missionDone===true;result=null;if(ran)simulate();else render();if(missionDone)evaluate();adapt();},afterRestore:()=>{if(ran)simulate();if(missionDone)evaluate();},activate:({restored})=>{const {level,supports}=window.TechEduCurrent();if(!restored){$('showSteps').checked=level==='guided'||supports.stepByStep;$('reveal').checked=!(level==='guided'||supports.hideSolution);$('showTruth').checked=false;}adapt();render();$('workPrediction').parentElement.firstChild.textContent='Predicció: amb el mateix patró, augmentar els reintents recuperarà els paquets perduts? Com canviarà el nombre total de bits?';$('workConclusion').parentElement.firstChild.textContent='Evidència: anota mida, protecció, reintents, paquets recuperats, bits i temps. Justifica si la proposta compleix el repte en tots tres patrons.';}};
 window.addEventListener('techedu-level',adapt);adapt();render();
})();
