import {defaults,clean,solve,fmt,schematic} from './model.mjs';
import {workspace,downloadJSON,sendToWorksheet} from '../../shared/workspace.mjs';
const $=s=>document.querySelector(s);let state=defaults(),store;
function guide(){const c=TechEduCurrent(),guided=c.level==='guided'||c.supports.stepByStep;$('#activityTitle').textContent=c.level==='extension'?'Repte: mateixa font, dues connexions':'Investiga la intensitat del circuit';$('#guide').textContent=guided?'1. Tanca l’interruptor. 2. Anota la tensió i cada resistència. 3. En sèrie, suma les resistències; en paral·lel, suma els inversos i inverteix el resultat; en el mixt, calcula primer R2 ∥ R3 i després suma R1. 4. Divideix la tensió per la resistència equivalent: I = U / Req. 5. Duplica una resistència: creus que I augmentarà o disminuirà? Comprova-ho.':c.level==='extension'?'Compara sèrie i paral·lel amb les mateixes resistències i tensió. Justifica quina connexió consumeix més potència. Dissenya un circuit mixt que limiti I a 0,1 A amb una font de 12 V; comprova la teva proposta.':'Calcula la resistència equivalent i la intensitat total. Duplica R1 mantenint la resta i compara les dues intensitats. Explica la diferència segons el tipus de connexió.';}
function render(){$('#feedback').textContent='';$('#inputError').textContent='';for(const k of ['topology','voltage','prediction','conclusion','answer'])$('#'+k).value=state[k];for(const k of ['closed','hide'])$('#'+k).checked=state[k];$('#count').value=state.resistors.length;$('#count').disabled=state.topology==='mixed';$('#resistors').innerHTML=state.resistors.map((v,i)=>`<label>R${i+1} (Ω)<input data-r="${i}" type="number" min="1" max="100000" step="1" value="${v}"></label>`).join('');outputs();guide()}
function outputs(){const r=solve(state);$('#diagram').innerHTML=schematic(state);$('#results').hidden=state.hide;$('#hiddenNotice').hidden=!state.hide;$('#metrics').innerHTML=[['Resistència equivalent',fmt(r.equivalent)+' Ω'],['Intensitat total',fmt(r.current)+' A'],['Potència total',fmt(r.power)+' W']].map(([t,v])=>`<div class="metric">${t}<strong>${v}</strong></div>`).join('');$('#rows').innerHTML=r.rows.map((x,i)=>`<tr><td>R${i+1}</td><td>${fmt(x.r)}</td><td>${fmt(x.v)}</td><td>${fmt(x.i)}</td><td>${fmt(x.p)}</td></tr>`).join('');$('#formula').textContent=(state.topology==='series'?'Req = R1 + R2 + …':state.topology==='parallel'?'1/Req = 1/R1 + 1/R2 + …':'Req = R1 + 1/(1/R2 + 1/R3)')+'. Amb el circuit tancat: I = U/Req; P = U·I.';}
store=workspace('circuits',defaults,clean,s=>{state=s;render()});window.addEventListener('techedu-level',guide);
$('main').addEventListener('change',e=>{const t=e.target,k=t.id;if(t.dataset.r!==undefined||k==='voltage'){const n=Number(t.value),min=k==='voltage'?0:1,max=k==='voltage'?48:100000;if(!t.value||!Number.isFinite(n)||n<min||n>max){$('#inputError').textContent=`Introdueix un valor entre ${min} i ${max}.`;t.value=k==='voltage'?state.voltage:state.resistors[+t.dataset.r];return}if(k==='voltage')state.voltage=n;else state.resistors[+t.dataset.r]=n;}else if(k==='topology'){state.topology=t.value;if(t.value==='mixed')state.resistors=[state.resistors[0],state.resistors[1],state.resistors[2]??100];render()}else if(k==='count'){state.resistors=Array.from({length:+t.value},(_,i)=>state.resistors[i]??100);render()}else if(['closed','hide'].includes(k))state[k]=t.checked;else return;$('#inputError').textContent='';$('#feedback').textContent='';outputs();store.save(state)});
for(const k of ['prediction','conclusion','answer'])$('#'+k).oninput=e=>{state[k]=e.target.value;if(k==='answer')$('#feedback').textContent='';store.save(state)};
$('#check').onclick=()=>{const expected=solve(state).current,a=Number(state.answer.trim().replace(',','.'));$('#feedback').textContent=!state.answer.trim()||!Number.isFinite(a)?'Escriu una intensitat en amperes.':(expected===0?a===0:a>=0&&Math.abs(a-expected)<=Math.max(1e-12,Math.abs(expected)*.015))?'Correcte dins del marge d’arrodoniment. Justifica ara el procediment.':state.closed?'Revisa Req i aplica I = U / Req. El resultat s’ha d’expressar en A.':'Un circuit obert no deixa circular corrent.';};
$('#reset').onclick=()=>{if((state.prediction||state.conclusion)&&!confirm('Carregar el repte substituirà el circuit i les respostes actuals. Continua?'))return;const c=TechEduCurrent();state=defaults();if(c.level==='guided')state.resistors=[100,100];if(c.level==='extension'){state.topology='mixed';state.resistors=[100,200,200]}state.hide=true;render();$('#feedback').textContent='';store.save(state)};
$('#export').onclick=()=>downloadJSON({format:'techedu-circuit',version:1,state},'circuitlab.json');
$('#import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100000)throw Error('Fitxer massa gran.');const j=JSON.parse(await f.text());if(j.format!=='techedu-circuit'||j.version!==1||!j.state)throw Error('Format de circuit no vàlid.');const x=j.state;if(!['series','parallel','mixed'].includes(x.topology)||!Number.isFinite(x.voltage)||x.voltage<0||x.voltage>48||!Array.isArray(x.resistors)||x.resistors.length<2||x.resistors.length>4||x.resistors.some(r=>!Number.isFinite(r)||r<1||r>100000)||(x.topology==='mixed'&&x.resistors.length!==3)||typeof x.closed!=='boolean')throw Error('Valors del circuit no vàlids.');if(!confirm('Substituir el circuit actual pel fitxer?'))return;state=clean(j.state);if(state.topology==='mixed')state.resistors=solve(state).resistors;render();store.save(state)}catch(e){$('#inputError').textContent=e.message}finally{e.target.value=''}};
$('#worksheet').onclick=()=>{try{
 const r=solve(state),level=TechEduCurrent().level,names={series:'sèrie',parallel:'paral·lel',mixed:'mixt: R1 + (R2 ∥ R3)'};
 let prompt='Calcula Req, la intensitat total i la potència total del circuit representat. Indica també la tensió i la intensitat de cada resistència.';
 let solution=`Req = ${fmt(r.equivalent)} Ω; I = ${fmt(r.current)} A; P = ${fmt(r.power)} W.\n`+r.rows.map((x,i)=>`R${i+1}: U = ${fmt(x.v)} V; I = ${fmt(x.i)} A; P = ${fmt(x.p)} W.`).join('\n');
 if(level==='guided')prompt+='\n1. Observa si l’interruptor és obert o tancat.\n2. Calcula Req amb la fórmula de la connexió.\n3. Si és tancat, aplica I = U / Req; si és obert, I = 0.\n4. Calcula P = U × I. Comprova les unitats.';
 if(level==='extension'){
  const a=solve({...state,closed:true,topology:'series'}),b=solve({...state,closed:true,topology:'parallel'});
  prompt+='\nAmpliació: amb l’interruptor tancat, compara les mateixes resistències totes en sèrie i totes en paral·lel. Calcula la potència total de cada cas. Després proposa un circuit R1 + (R2 ∥ R3) que consumeixi 0,1 A amb una font de 12 V.';
  solution+=`\nComparació amb l’interruptor tancat: sèrie, Req = ${fmt(a.equivalent)} Ω, I = ${fmt(a.current)} A, P = ${fmt(a.power)} W; paral·lel, Req = ${fmt(b.equivalent)} Ω, I = ${fmt(b.current)} A, P = ${fmt(b.power)} W. Exemple de disseny: R1 = 60 Ω, R2 = R3 = 120 Ω; Req = 120 Ω, I = 0,1 A. S’accepten altres combinacions equivalents.`;
 }else{
  const changed=solve({...state,closed:true,resistors:state.resistors.map((v,i)=>i===0?Math.min(100000,v*2):v)}),base=solve({...state,closed:true});
  const newR=Math.min(100000,state.resistors[0]*2);
  prompt+=`\nCompara dos circuits amb l’interruptor tancat: primer els valors inicials, després R1 = ${fmt(newR)} Ω mantenint la resta. Com canvia I?`;
  solution+=`\nComparació amb l’interruptor tancat: I inicial = ${fmt(base.current)} A; amb R1 = ${fmt(newR)} Ω, Req = ${fmt(changed.equivalent)} Ω i I = ${fmt(changed.current)} A. Amb tensió positiva, augmentar R1 augmenta Req i redueix I; si U = 0, I és zero en tots dos casos. Si R1 ja és 100 kΩ, el límit del laboratori manté el mateix valor.`;
 }
 sendToWorksheet([{type:'image',title:'Circuit '+names[state.topology],prompt:`Font de ${fmt(state.voltage)} V. Interruptor ${state.closed?'tancat':'obert'}. `+r.resistors.map((v,i)=>`R${i+1} = ${fmt(v)} Ω`).join('; ')+'.',image:'data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(schematic(state))))},{type:'question',title:'Analitza el circuit',prompt,solution,space:2}]);
}catch(e){$('#inputError').textContent='No s’ha pogut transferir la fitxa: '+e.message}};
